import { Team, Driver, Race, RaceResult } from '@/types';

export const TEAMS: Team[] = [
  { id: 'mclaren', name: 'McLaren', color: '#FF8000', shortName: 'MCL' },
  { id: 'ferrari', name: 'Scuderia Ferrari', color: '#E8002D', shortName: 'FER' },
  { id: 'red-bull', name: 'Red Bull Racing', color: '#3671C6', shortName: 'RBR' },
  { id: 'mercedes', name: 'Mercedes-AMG', color: '#27F4D2', shortName: 'MER' },
  { id: 'aston-martin', name: 'Aston Martin', color: '#229971', shortName: 'AMR' },
  { id: 'alpine', name: 'Alpine', color: '#FF87BC', shortName: 'ALP' },
  { id: 'williams', name: 'Williams', color: '#64C4FF', shortName: 'WIL' },
  { id: 'racing-bulls', name: 'Racing Bulls', color: '#6692FF', shortName: 'RB' },
  { id: 'sauber', name: 'Sauber', color: '#00E600', shortName: 'SAU' },
  { id: 'haas', name: 'Haas', color: '#B6BABD', shortName: 'HAA' },
];

// 2025 FIA Formula One World Championship — final driver standings.
// Sourced from Jolpica/Ergast API (verified against formula1.com).
export const DRIVERS: Driver[] = [
  { id: 'NOR', name: 'Lando Norris', shortName: 'NOR', number: 4, teamId: 'mclaren', championshipPoints: 423 },
  { id: 'VER', name: 'Max Verstappen', shortName: 'VER', number: 1, teamId: 'red-bull', championshipPoints: 421 },
  { id: 'PIA', name: 'Oscar Piastri', shortName: 'PIA', number: 81, teamId: 'mclaren', championshipPoints: 410 },
  { id: 'RUS', name: 'George Russell', shortName: 'RUS', number: 63, teamId: 'mercedes', championshipPoints: 319 },
  { id: 'LEC', name: 'Charles Leclerc', shortName: 'LEC', number: 16, teamId: 'ferrari', championshipPoints: 242 },
  { id: 'HAM', name: 'Lewis Hamilton', shortName: 'HAM', number: 44, teamId: 'ferrari', championshipPoints: 156 },
  { id: 'ANT', name: 'Kimi Antonelli', shortName: 'ANT', number: 12, teamId: 'mercedes', championshipPoints: 150 },
  { id: 'ALB', name: 'Alex Albon', shortName: 'ALB', number: 23, teamId: 'williams', championshipPoints: 73 },
  { id: 'SAI', name: 'Carlos Sainz', shortName: 'SAI', number: 55, teamId: 'williams', championshipPoints: 64 },
  { id: 'ALO', name: 'Fernando Alonso', shortName: 'ALO', number: 14, teamId: 'aston-martin', championshipPoints: 56 },
  { id: 'HUL', name: 'Nico Hulkenberg', shortName: 'HUL', number: 27, teamId: 'sauber', championshipPoints: 51 },
  { id: 'HAD', name: 'Isack Hadjar', shortName: 'HAD', number: 6, teamId: 'racing-bulls', championshipPoints: 51 },
  { id: 'BEA', name: 'Oliver Bearman', shortName: 'BEA', number: 87, teamId: 'haas', championshipPoints: 41 },
  { id: 'LAW', name: 'Liam Lawson', shortName: 'LAW', number: 30, teamId: 'red-bull', championshipPoints: 38 },
  { id: 'OCO', name: 'Esteban Ocon', shortName: 'OCO', number: 31, teamId: 'haas', championshipPoints: 38 },
  { id: 'STR', name: 'Lance Stroll', shortName: 'STR', number: 18, teamId: 'aston-martin', championshipPoints: 33 },
  { id: 'TSU', name: 'Yuki Tsunoda', shortName: 'TSU', number: 22, teamId: 'racing-bulls', championshipPoints: 33 },
  { id: 'GAS', name: 'Pierre Gasly', shortName: 'GAS', number: 10, teamId: 'alpine', championshipPoints: 22 },
  { id: 'BOR', name: 'Gabriel Bortoleto', shortName: 'BOR', number: 5, teamId: 'sauber', championshipPoints: 19 },
  { id: 'COL', name: 'Franco Colapinto', shortName: 'COL', number: 43, teamId: 'alpine', championshipPoints: 0 },
  { id: 'DOO', name: 'Jack Doohan', shortName: 'DOO', number: 7, teamId: 'alpine', championshipPoints: 0 },
];

// 2025 FIA Formula One World Championship calendar.
// Dates and sprint flags verified against formula1.com and Jolpica/Ergast API.
export const RACES: Race[] = [
  { id: 'r01', round: 1,  name: 'Australian Grand Prix',      location: 'Melbourne',        country: 'Australia',       countryFlag: '', raceDate: '2025-03-16', raceTime: '04:00', status: 'completed', hasSprint: false, winner: 'NOR', totalLaps: 57 },
  { id: 'r02', round: 2,  name: 'Chinese Grand Prix',          location: 'Shanghai',         country: 'China',           countryFlag: '', raceDate: '2025-03-23', raceTime: '07:00', status: 'completed', hasSprint: true,  winner: 'PIA', totalLaps: 56 },
  { id: 'r03', round: 3,  name: 'Japanese Grand Prix',         location: 'Suzuka',           country: 'Japan',           countryFlag: '', raceDate: '2025-04-06', raceTime: '05:00', status: 'completed', hasSprint: false, winner: 'VER', totalLaps: 53 },
  { id: 'r04', round: 4,  name: 'Bahrain Grand Prix',          location: 'Sakhir',           country: 'Bahrain',         countryFlag: '', raceDate: '2025-04-13', raceTime: '16:00', status: 'completed', hasSprint: false, winner: 'PIA', totalLaps: 57 },
  { id: 'r05', round: 5,  name: 'Saudi Arabian Grand Prix',    location: 'Jeddah',           country: 'Saudi Arabia',    countryFlag: '', raceDate: '2025-04-20', raceTime: '18:00', status: 'completed', hasSprint: false, winner: 'PIA', totalLaps: 50 },
  { id: 'r06', round: 6,  name: 'Miami Grand Prix',            location: 'Miami',            country: 'USA',             countryFlag: '', raceDate: '2025-05-04', raceTime: '20:00', status: 'completed', hasSprint: true,  winner: 'PIA', totalLaps: 57 },
  { id: 'r07', round: 7,  name: 'Emilia Romagna Grand Prix',   location: 'Imola',            country: 'Italy',           countryFlag: '', raceDate: '2025-05-18', raceTime: '13:00', status: 'completed', hasSprint: false, winner: 'VER', totalLaps: 63 },
  { id: 'r08', round: 8,  name: 'Monaco Grand Prix',           location: 'Monte Carlo',      country: 'Monaco',          countryFlag: '', raceDate: '2025-05-25', raceTime: '13:00', status: 'completed', hasSprint: false, winner: 'NOR', totalLaps: 78 },
  { id: 'r09', round: 9,  name: 'Spanish Grand Prix',          location: 'Barcelona',        country: 'Spain',           countryFlag: '', raceDate: '2025-06-01', raceTime: '13:00', status: 'completed', hasSprint: false, winner: 'PIA', totalLaps: 66 },
  { id: 'r10', round: 10, name: 'Canadian Grand Prix',         location: 'Montreal',         country: 'Canada',          countryFlag: '', raceDate: '2025-06-15', raceTime: '18:00', status: 'completed', hasSprint: false, winner: 'RUS', totalLaps: 70 },
  { id: 'r11', round: 11, name: 'Austrian Grand Prix',         location: 'Spielberg',        country: 'Austria',         countryFlag: '', raceDate: '2025-06-29', raceTime: '13:00', status: 'completed', hasSprint: false, winner: 'PIA', totalLaps: 71 },
  { id: 'r12', round: 12, name: 'British Grand Prix',          location: 'Silverstone',      country: 'United Kingdom',  countryFlag: '', raceDate: '2025-07-06', raceTime: '14:00', status: 'completed', hasSprint: false, winner: 'NOR', totalLaps: 52 },
  { id: 'r13', round: 13, name: 'Belgian Grand Prix',          location: 'Spa-Francorchamps', country: 'Belgium',        countryFlag: '', raceDate: '2025-07-27', raceTime: '13:00', status: 'completed', hasSprint: true,  winner: 'PIA', totalLaps: 44 },
  { id: 'r14', round: 14, name: 'Hungarian Grand Prix',        location: 'Budapest',         country: 'Hungary',         countryFlag: '', raceDate: '2025-08-03', raceTime: '13:00', status: 'completed', hasSprint: false, winner: 'NOR', totalLaps: 70 },
  { id: 'r15', round: 15, name: 'Dutch Grand Prix',            location: 'Zandvoort',        country: 'Netherlands',     countryFlag: '', raceDate: '2025-08-31', raceTime: '13:00', status: 'completed', hasSprint: false, winner: 'PIA', totalLaps: 72 },
  { id: 'r16', round: 16, name: 'Italian Grand Prix',          location: 'Monza',            country: 'Italy',           countryFlag: '', raceDate: '2025-09-07', raceTime: '13:00', status: 'completed', hasSprint: false, winner: 'NOR', totalLaps: 53 },
  { id: 'r17', round: 17, name: 'Azerbaijan Grand Prix',       location: 'Baku',             country: 'Azerbaijan',      countryFlag: '', raceDate: '2025-09-21', raceTime: '12:00', status: 'completed', hasSprint: false, winner: 'VER', totalLaps: 51 },
  { id: 'r18', round: 18, name: 'Singapore Grand Prix',        location: 'Marina Bay',       country: 'Singapore',       countryFlag: '', raceDate: '2025-10-05', raceTime: '12:00', status: 'completed', hasSprint: false, winner: 'RUS', totalLaps: 62 },
  { id: 'r19', round: 19, name: 'United States Grand Prix',    location: 'Austin',           country: 'USA',             countryFlag: '', raceDate: '2025-10-19', raceTime: '19:00', status: 'completed', hasSprint: true,  winner: 'VER', totalLaps: 56 },
  { id: 'r20', round: 20, name: 'Mexico City Grand Prix',      location: 'Mexico City',      country: 'Mexico',          countryFlag: '', raceDate: '2025-10-26', raceTime: '20:00', status: 'completed', hasSprint: false, winner: 'NOR', totalLaps: 71 },
  { id: 'r21', round: 21, name: 'São Paulo Grand Prix',        location: 'Interlagos',       country: 'Brazil',          countryFlag: '', raceDate: '2025-11-09', raceTime: '17:00', status: 'completed', hasSprint: true,  winner: 'ANT', totalLaps: 71 },
  { id: 'r22', round: 22, name: 'Las Vegas Grand Prix',        location: 'Las Vegas',        country: 'USA',             countryFlag: '', raceDate: '2025-11-23', raceTime: '06:00', status: 'completed', hasSprint: false, winner: 'VER', totalLaps: 50 },
  { id: 'r23', round: 23, name: 'Qatar Grand Prix',            location: 'Lusail',           country: 'Qatar',           countryFlag: '', raceDate: '2025-11-30', raceTime: '17:00', status: 'completed', hasSprint: false, winner: 'VER', totalLaps: 57 },
  { id: 'r24', round: 24, name: 'Abu Dhabi Grand Prix',        location: 'Yas Marina',       country: 'UAE',             countryFlag: '', raceDate: '2025-12-07', raceTime: '14:00', status: 'completed', hasSprint: false, winner: 'VER', totalLaps: 58 },
];

/**
 * 2025 FIA Formula One World Championship — verified race results.
 * Sourced from Jolpica/Ergast API and cross-checked against formula1.com.
 *
 * Used as fallback when the live API doesn't return data.
 * The live Jolpica API is the authoritative source — this data fills gaps.
 *
 * DNS is separate from DNF:
 * - DNS drivers use status: 'dns'
 * - DNS drivers are listed in dnsDriverIds
 * - DNS drivers are NOT listed in dnfDriverIds
 */
export const MOCK_RACE_RESULTS: RaceResult[] = [
  // R01 — Australian GP — 2025-03-16
  { raceId: 'r01', classification: [
    { position: 1, driverId: 'NOR', time: '1:42:06.304', gap: 'Leader', points: 25, status: 'finished' as const },
    { position: 2, driverId: 'VER', time: '1:42:07.199', gap: '+0.895s', points: 18, status: 'finished' as const },
    { position: 3, driverId: 'RUS', time: '1:42:14.785', gap: '+8.481s', points: 15, status: 'finished' as const },
    { position: 4, driverId: 'ANT', time: '1:42:16.439', gap: '+10.135s', points: 12, status: 'finished' as const },
    { position: 5, driverId: 'ALB', time: '1:42:19.077', gap: '+12.773s', points: 10, status: 'finished' as const },
    { position: 6, driverId: 'STR', time: '1:42:23.717', gap: '+17.413s', points: 8, status: 'finished' as const },
    { position: 7, driverId: 'HUL', time: '1:42:24.727', gap: '+18.423s', points: 6, status: 'finished' as const },
    { position: 8, driverId: 'LEC', time: '1:42:26.130', gap: '+19.826s', points: 4, status: 'finished' as const },
    { position: 9, driverId: 'PIA', time: '1:42:26.752', gap: '+20.448s', points: 2, status: 'finished' as const },
    { position: 10, driverId: 'HAM', time: '1:42:28.777', gap: '+22.473s', points: 1, status: 'finished' as const },
    { position: 11, driverId: 'GAS', time: '1:42:32.806', gap: '+26.502s', points: 0, status: 'finished' as const },
    { position: 12, driverId: 'TSU', time: '1:42:36.188', gap: '+29.884s', points: 0, status: 'finished' as const },
    { position: 13, driverId: 'OCO', time: '1:42:39.465', gap: '+33.161s', points: 0, status: 'finished' as const },
    { position: 14, driverId: 'BEA', time: '1:42:46.655', gap: '+40.351s', points: 0, status: 'finished' as const },
    { position: 15, driverId: 'LAW', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
    { position: 16, driverId: 'BOR', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
    { position: 17, driverId: 'ALO', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
    { position: 18, driverId: 'SAI', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
    { position: 19, driverId: 'DOO', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
    { position: 20, driverId: 'HAD', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
  ], fastestLapDriverId: 'NOR', dnfDriverIds: ['LAW', 'BOR', 'ALO', 'SAI', 'DOO', 'HAD'], dnsDriverIds: [] },

  // R02 — Chinese GP — 2025-03-23 — SPRINT
  { raceId: 'r02', classification: [
    { position: 1, driverId: 'PIA', time: '1:30:55.026', gap: 'Leader', points: 25, status: 'finished' as const },
    { position: 2, driverId: 'NOR', time: '1:31:04.774', gap: '+9.748s', points: 18, status: 'finished' as const },
    { position: 3, driverId: 'RUS', time: '1:31:06.123', gap: '+11.097s', points: 15, status: 'finished' as const },
    { position: 4, driverId: 'VER', time: '1:31:11.682', gap: '+16.656s', points: 12, status: 'finished' as const },
    { position: 5, driverId: 'OCO', time: '1:31:44.995', gap: '+49.969s', points: 10, status: 'finished' as const },
    { position: 6, driverId: 'ANT', time: '1:31:48.774', gap: '+53.748s', points: 8, status: 'finished' as const },
    { position: 7, driverId: 'ALB', time: '1:31:51.347', gap: '+56.321s', points: 6, status: 'finished' as const },
    { position: 8, driverId: 'BEA', time: '1:31:56.329', gap: '+61.303s', points: 4, status: 'finished' as const },
    { position: 9, driverId: 'STR', time: '1:32:05.230', gap: '+70.204s', points: 2, status: 'finished' as const },
    { position: 10, driverId: 'SAI', time: '1:32:11.413', gap: '+76.387s', points: 1, status: 'finished' as const },
    { position: 11, driverId: 'HAD', time: '1:32:13.901', gap: '+78.875s', points: 0, status: 'finished' as const },
    { position: 12, driverId: 'LAW', time: '1:32:16.173', gap: '+81.147s', points: 0, status: 'finished' as const },
    { position: 13, driverId: 'DOO', time: '1:32:23.427', gap: '+88.401s', points: 0, status: 'finished' as const },
    { position: 14, driverId: 'BOR', time: '+1 lap', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 15, driverId: 'HUL', time: '+1 lap', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 16, driverId: 'TSU', time: '+1 lap', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 17, driverId: 'ALO', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
    { position: 18, driverId: 'LEC', time: '', gap: 'DSQ', points: 0, status: 'dnf' as const },
    { position: 19, driverId: 'HAM', time: '', gap: 'DSQ', points: 0, status: 'dnf' as const },
    { position: 20, driverId: 'GAS', time: '', gap: 'DSQ', points: 0, status: 'dnf' as const },
  ], fastestLapDriverId: 'NOR', dnfDriverIds: ['ALO', 'LEC', 'HAM', 'GAS'], dnsDriverIds: [],
    sprintClassification: [
      { position: 1, driverId: 'HAM', time: '30:39.121', gap: 'Leader', points: 8, status: 'finished' as const },
      { position: 2, driverId: 'PIA', time: '30:40.386', gap: '+1.265s', points: 7, status: 'finished' as const },
      { position: 3, driverId: 'VER', time: '30:40.756', gap: '+1.635s', points: 6, status: 'finished' as const },
      { position: 4, driverId: 'RUS', time: '30:41.311', gap: '+2.190s', points: 5, status: 'finished' as const },
      { position: 5, driverId: 'LEC', time: '30:41.542', gap: '+2.421s', points: 4, status: 'finished' as const },
      { position: 6, driverId: 'TSU', time: '30:42.623', gap: '+3.502s', points: 3, status: 'finished' as const },
      { position: 7, driverId: 'ANT', time: '30:43.152', gap: '+4.031s', points: 2, status: 'finished' as const },
      { position: 8, driverId: 'NOR', time: '30:44.358', gap: '+5.237s', points: 1, status: 'finished' as const },
    ] },

  // R03 — Japanese GP — 2025-04-06
  { raceId: 'r03', classification: [
    { position: 1, driverId: 'VER', time: '1:22:06.983', gap: 'Leader', points: 25, status: 'finished' as const },
    { position: 2, driverId: 'NOR', time: '1:22:08.406', gap: '+1.423s', points: 18, status: 'finished' as const },
    { position: 3, driverId: 'PIA', time: '1:22:09.112', gap: '+2.129s', points: 15, status: 'finished' as const },
    { position: 4, driverId: 'LEC', time: '1:22:23.080', gap: '+16.097s', points: 12, status: 'finished' as const },
    { position: 5, driverId: 'RUS', time: '1:22:24.345', gap: '+17.362s', points: 10, status: 'finished' as const },
    { position: 6, driverId: 'ANT', time: '1:22:25.654', gap: '+18.671s', points: 8, status: 'finished' as const },
    { position: 7, driverId: 'HAM', time: '1:22:36.165', gap: '+29.182s', points: 6, status: 'finished' as const },
    { position: 8, driverId: 'HAD', time: '1:22:44.117', gap: '+37.134s', points: 4, status: 'finished' as const },
    { position: 9, driverId: 'ALB', time: '1:22:47.350', gap: '+40.367s', points: 2, status: 'finished' as const },
    { position: 10, driverId: 'BEA', time: '1:23:01.512', gap: '+54.529s', points: 1, status: 'finished' as const },
    { position: 11, driverId: 'ALO', time: '1:23:04.316', gap: '+57.333s', points: 0, status: 'finished' as const },
    { position: 12, driverId: 'TSU', time: '1:23:05.384', gap: '+58.401s', points: 0, status: 'finished' as const },
    { position: 13, driverId: 'GAS', time: '1:23:09.105', gap: '+62.122s', points: 0, status: 'finished' as const },
    { position: 14, driverId: 'SAI', time: '1:23:21.112', gap: '+74.129s', points: 0, status: 'finished' as const },
    { position: 15, driverId: 'DOO', time: '1:23:28.297', gap: '+81.314s', points: 0, status: 'finished' as const },
    { position: 16, driverId: 'HUL', time: '1:23:28.940', gap: '+81.957s', points: 0, status: 'finished' as const },
    { position: 17, driverId: 'LAW', time: '1:23:35.603', gap: '+88.620s', points: 0, status: 'finished' as const },
    { position: 18, driverId: 'STR', time: '1:23:42.710', gap: '+95.727s', points: 0, status: 'finished' as const },
    { position: 19, driverId: 'BOR', time: '1:22:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 20, driverId: 'OCO', time: '1:22:--', gap: '+1 lap', points: 0, status: 'finished' as const },
  ], fastestLapDriverId: 'ANT', dnfDriverIds: [], dnsDriverIds: [] },

  // R04 — Bahrain GP — 2025-04-13
  { raceId: 'r04', classification: [
    { position: 1, driverId: 'PIA', time: '1:35:39.435', gap: 'Leader', points: 25, status: 'finished' as const },
    { position: 2, driverId: 'RUS', time: '1:35:43.121', gap: '+3.686s', points: 18, status: 'finished' as const },
    { position: 3, driverId: 'NOR', time: '1:35:50.233', gap: '+10.798s', points: 15, status: 'finished' as const },
    { position: 4, driverId: 'LEC', time: '1:36:01.470', gap: '+22.035s', points: 12, status: 'finished' as const },
    { position: 5, driverId: 'HAM', time: '1:36:11.892', gap: '+32.457s', points: 10, status: 'finished' as const },
    { position: 6, driverId: 'VER', time: '1:36:29.013', gap: '+49.578s', points: 8, status: 'finished' as const },
    { position: 7, driverId: 'GAS', time: '1:36:33.552', gap: '+54.117s', points: 6, status: 'finished' as const },
    { position: 8, driverId: 'OCO', time: '1:36:42.142', gap: '+62.707s', points: 4, status: 'finished' as const },
    { position: 9, driverId: 'TSU', time: '1:36:49.463', gap: '+70.028s', points: 2, status: 'finished' as const },
    { position: 10, driverId: 'BEA', time: '1:35:--', gap: '+1 lap', points: 1, status: 'finished' as const },
    { position: 11, driverId: 'HUL', time: '1:35:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 12, driverId: 'ALB', time: '1:35:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 13, driverId: 'DOO', time: '1:36:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 14, driverId: 'STR', time: '1:36:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 15, driverId: 'LAW', time: '1:36:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 16, driverId: 'BOR', time: '1:36:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 17, driverId: 'ALO', time: '1:36:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 18, driverId: 'HAD', time: '1:36:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 19, driverId: 'ANT', time: '1:36:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 20, driverId: 'SAI', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
    { position: 21, driverId: 'COL', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
  ], fastestLapDriverId: 'PIA', dnfDriverIds: ['SAI', 'COL'], dnsDriverIds: [] },

  // R05 — Saudi Arabian GP — 2025-04-20
  { raceId: 'r05', classification: [
    { position: 1, driverId: 'PIA', time: '1:21:06.758', gap: 'Leader', points: 25, status: 'finished' as const },
    { position: 2, driverId: 'VER', time: '1:21:10.255', gap: '+3.497s', points: 18, status: 'finished' as const },
    { position: 3, driverId: 'LEC', time: '1:21:14.489', gap: '+7.731s', points: 15, status: 'finished' as const },
    { position: 4, driverId: 'NOR', time: '1:21:16.932', gap: '+10.174s', points: 12, status: 'finished' as const },
    { position: 5, driverId: 'RUS', time: '1:21:23.115', gap: '+16.357s', points: 10, status: 'finished' as const },
    { position: 6, driverId: 'ANT', time: '1:21:25.311', gap: '+18.553s', points: 8, status: 'finished' as const },
    { position: 7, driverId: 'HAM', time: '1:21:26.446', gap: '+19.688s', points: 6, status: 'finished' as const },
    { position: 8, driverId: 'SAI', time: '1:21:30.890', gap: '+24.132s', points: 4, status: 'finished' as const },
    { position: 9, driverId: 'ALB', time: '1:21:37.956', gap: '+31.198s', points: 2, status: 'finished' as const },
    { position: 10, driverId: 'HAD', time: '1:21:45.827', gap: '+39.069s', points: 1, status: 'finished' as const },
    { position: 11, driverId: 'LAW', time: '1:21:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 12, driverId: 'ALO', time: '1:21:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 13, driverId: 'BEA', time: '1:21:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 14, driverId: 'STR', time: '1:21:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 15, driverId: 'OCO', time: '1:21:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 16, driverId: 'HUL', time: '1:22:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 17, driverId: 'DOO', time: '1:22:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 18, driverId: 'BOR', time: '1:22:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 19, driverId: 'TSU', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
    { position: 20, driverId: 'GAS', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
  ], fastestLapDriverId: 'NOR', dnfDriverIds: ['TSU', 'GAS'], dnsDriverIds: [] },

  // R06 — Miami GP — 2025-05-04 — SPRINT
  { raceId: 'r06', classification: [
    { position: 1, driverId: 'PIA', time: '1:28:51.587', gap: 'Leader', points: 25, status: 'finished' as const },
    { position: 2, driverId: 'NOR', time: '1:28:53.734', gap: '+2.147s', points: 18, status: 'finished' as const },
    { position: 3, driverId: 'RUS', time: '1:28:56.810', gap: '+5.223s', points: 15, status: 'finished' as const },
    { position: 4, driverId: 'VER', time: '1:29:04.479', gap: '+12.892s', points: 12, status: 'finished' as const },
    { position: 5, driverId: 'ALB', time: '1:29:16.623', gap: '+25.036s', points: 10, status: 'finished' as const },
    { position: 6, driverId: 'ANT', time: '1:29:21.049', gap: '+29.462s', points: 8, status: 'finished' as const },
    { position: 7, driverId: 'LEC', time: '1:29:35.785', gap: '+44.198s', points: 6, status: 'finished' as const },
    { position: 8, driverId: 'HAM', time: '1:29:48.265', gap: '+56.678s', points: 4, status: 'finished' as const },
    { position: 9, driverId: 'SAI', time: '1:30:04.208', gap: '+72.621s', points: 2, status: 'finished' as const },
    { position: 10, driverId: 'TSU', time: '1:28:--', gap: '+1 lap', points: 1, status: 'finished' as const },
    { position: 11, driverId: 'HAD', time: '1:28:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 12, driverId: 'GAS', time: '1:28:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 13, driverId: 'ALO', time: '1:29:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 14, driverId: 'HUL', time: '1:29:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 15, driverId: 'STR', time: '1:29:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 16, driverId: 'OCO', time: '1:29:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 17, driverId: 'LAW', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
    { position: 18, driverId: 'BOR', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
    { position: 19, driverId: 'BEA', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
    { position: 20, driverId: 'DOO', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
  ], fastestLapDriverId: 'NOR', dnfDriverIds: ['LAW', 'BOR', 'BEA', 'DOO'], dnsDriverIds: [],
    sprintClassification: [
      { position: 1, driverId: 'NOR', time: '29:15.045', gap: 'Leader', points: 8, status: 'finished' as const },
      { position: 2, driverId: 'PIA', time: '29:18.811', gap: '+3.766s', points: 7, status: 'finished' as const },
      { position: 3, driverId: 'HAM', time: '29:20.996', gap: '+5.951s', points: 6, status: 'finished' as const },
      { position: 4, driverId: 'RUS', time: '29:23.555', gap: '+8.510s', points: 5, status: 'finished' as const },
      { position: 5, driverId: 'STR', time: '29:28.811', gap: '+13.766s', points: 4, status: 'finished' as const },
      { position: 6, driverId: 'TSU', time: '29:30.295', gap: '+15.250s', points: 3, status: 'finished' as const },
      { position: 7, driverId: 'ANT', time: '29:30.753', gap: '+15.708s', points: 2, status: 'finished' as const },
      { position: 8, driverId: 'GAS', time: '29:33.015', gap: '+17.970s', points: 1, status: 'finished' as const },
    ] },

  // R07 — Emilia Romagna GP — 2025-05-18
  { raceId: 'r07', classification: [
    { position: 1, driverId: 'VER', time: '1:31:33.199', gap: 'Leader', points: 25, status: 'finished' as const },
    { position: 2, driverId: 'NOR', time: '1:31:35.971', gap: '+2.772s', points: 18, status: 'finished' as const },
    { position: 3, driverId: 'PIA', time: '1:31:44.612', gap: '+11.413s', points: 15, status: 'finished' as const },
    { position: 4, driverId: 'HAM', time: '1:31:52.235', gap: '+19.036s', points: 12, status: 'finished' as const },
    { position: 5, driverId: 'ALB', time: '1:32:02.407', gap: '+29.208s', points: 10, status: 'finished' as const },
    { position: 6, driverId: 'LEC', time: '1:32:07.056', gap: '+33.857s', points: 8, status: 'finished' as const },
    { position: 7, driverId: 'RUS', time: '1:32:14.815', gap: '+41.616s', points: 6, status: 'finished' as const },
    { position: 8, driverId: 'SAI', time: '1:32:23.567', gap: '+50.368s', points: 4, status: 'finished' as const },
    { position: 9, driverId: 'HAD', time: '1:32:45.647', gap: '+72.448s', points: 2, status: 'finished' as const },
    { position: 10, driverId: 'TSU', time: '1:31:--', gap: '+1 lap', points: 1, status: 'finished' as const },
    { position: 11, driverId: 'ALO', time: '1:31:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 12, driverId: 'GAS', time: '1:32:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 13, driverId: 'STR', time: '1:32:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 14, driverId: 'DOO', time: '1:32:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 15, driverId: 'LAW', time: '1:32:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 16, driverId: 'HUL', time: '1:32:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 17, driverId: 'BOR', time: '1:33:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 18, driverId: 'ANT', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
    { position: 19, driverId: 'OCO', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
  ], fastestLapDriverId: 'VER', dnfDriverIds: ['ANT', 'OCO'], dnsDriverIds: [] },

  // R08 — Monaco GP — 2025-05-25
  { raceId: 'r08', classification: [
    { position: 1, driverId: 'NOR', time: '1:40:33.843', gap: 'Leader', points: 25, status: 'finished' as const },
    { position: 2, driverId: 'LEC', time: '1:40:35.238', gap: '+1.395s', points: 18, status: 'finished' as const },
    { position: 3, driverId: 'PIA', time: '1:40:36.289', gap: '+2.446s', points: 15, status: 'finished' as const },
    { position: 4, driverId: 'VER', time: '1:40:41.179', gap: '+7.336s', points: 12, status: 'finished' as const },
    { position: 5, driverId: 'HAM', time: '1:40:43.218', gap: '+9.375s', points: 10, status: 'finished' as const },
    { position: 6, driverId: 'HAD', time: '1:40:47.500', gap: '+13.657s', points: 8, status: 'finished' as const },
    { position: 7, driverId: 'OCO', time: '1:40:52.910', gap: '+19.067s', points: 6, status: 'finished' as const },
    { position: 8, driverId: 'LAW', time: '1:41:04.423', gap: '+30.580s', points: 4, status: 'finished' as const },
    { position: 9, driverId: 'ALB', time: '1:41:05.910', gap: '+32.067s', points: 2, status: 'finished' as const },
    { position: 10, driverId: 'SAI', time: '1:41:11.078', gap: '+37.235s', points: 1, status: 'finished' as const },
    { position: 11, driverId: 'STR', time: '1:41:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 12, driverId: 'ANT', time: '1:41:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 13, driverId: 'BEA', time: '1:41:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 14, driverId: 'TSU', time: '1:41:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 15, driverId: 'BOR', time: '1:41:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 16, driverId: 'HUL', time: '1:41:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 17, driverId: 'DOO', time: '1:42:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 18, driverId: 'ALO', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
    { position: 19, driverId: 'GAS', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
  ], fastestLapDriverId: 'NOR', dnfDriverIds: ['ALO', 'GAS'], dnsDriverIds: [] },

  // R09 — Spanish GP — 2025-06-01
  { raceId: 'r09', classification: [
    { position: 1, driverId: 'PIA', time: '1:26:10.308', gap: 'Leader', points: 25, status: 'finished' as const },
    { position: 2, driverId: 'NOR', time: '1:26:13.887', gap: '+3.579s', points: 18, status: 'finished' as const },
    { position: 3, driverId: 'LEC', time: '1:26:24.085', gap: '+13.777s', points: 15, status: 'finished' as const },
    { position: 4, driverId: 'RUS', time: '1:26:28.676', gap: '+18.368s', points: 12, status: 'finished' as const },
    { position: 5, driverId: 'HUL', time: '1:26:40.638', gap: '+30.330s', points: 10, status: 'finished' as const },
    { position: 6, driverId: 'HAM', time: '1:26:46.226', gap: '+35.918s', points: 8, status: 'finished' as const },
    { position: 7, driverId: 'HAD', time: '1:26:52.156', gap: '+41.848s', points: 6, status: 'finished' as const },
    { position: 8, driverId: 'GAS', time: '1:27:01.158', gap: '+50.850s', points: 4, status: 'finished' as const },
    { position: 9, driverId: 'ALO', time: '1:27:05.476', gap: '+55.168s', points: 2, status: 'finished' as const },
    { position: 10, driverId: 'VER', time: '1:26:--', gap: '+1 lap', points: 1, status: 'finished' as const },
    { position: 11, driverId: 'STR', time: '1:26:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 12, driverId: 'SAI', time: '1:26:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 13, driverId: 'OCO', time: '1:26:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 14, driverId: 'BEA', time: '1:26:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 15, driverId: 'TSU', time: '1:26:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 16, driverId: 'DOO', time: '1:27:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 17, driverId: 'LAW', time: '1:27:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 18, driverId: 'BOR', time: '1:27:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 19, driverId: 'ANT', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
    { position: 20, driverId: 'ALB', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
  ], fastestLapDriverId: 'PIA', dnfDriverIds: ['ANT', 'ALB'], dnsDriverIds: [] },

  // R10 — Canadian GP — 2025-06-15
  { raceId: 'r10', classification: [
    { position: 1, driverId: 'RUS', time: '1:44:47.234', gap: 'Leader', points: 25, status: 'finished' as const },
    { position: 2, driverId: 'VER', time: '1:44:49.502', gap: '+2.268s', points: 18, status: 'finished' as const },
    { position: 3, driverId: 'ANT', time: '1:44:52.689', gap: '+5.455s', points: 15, status: 'finished' as const },
    { position: 4, driverId: 'PIA', time: '1:45:02.573', gap: '+15.339s', points: 12, status: 'finished' as const },
    { position: 5, driverId: 'LEC', time: '1:45:13.898', gap: '+26.664s', points: 10, status: 'finished' as const },
    { position: 6, driverId: 'HAM', time: '1:45:19.247', gap: '+32.013s', points: 8, status: 'finished' as const },
    { position: 7, driverId: 'ALO', time: '1:45:26.416', gap: '+39.182s', points: 6, status: 'finished' as const },
    { position: 8, driverId: 'HUL', time: '1:45:37.520', gap: '+50.286s', points: 4, status: 'finished' as const },
    { position: 9, driverId: 'OCO', time: '1:45:44.907', gap: '+57.673s', points: 2, status: 'finished' as const },
    { position: 10, driverId: 'SAI', time: '1:45:50.510', gap: '+63.276s', points: 1, status: 'finished' as const },
    { position: 11, driverId: 'STR', time: '1:44:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 12, driverId: 'GAS', time: '1:44:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 13, driverId: 'TSU', time: '1:44:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 14, driverId: 'DOO', time: '1:45:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 15, driverId: 'HAD', time: '1:45:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 16, driverId: 'BOR', time: '1:46:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 17, driverId: 'BEA', time: '1:46:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 18, driverId: 'NOR', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
    { position: 19, driverId: 'LAW', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
    { position: 20, driverId: 'ALB', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
  ], fastestLapDriverId: 'RUS', dnfDriverIds: ['NOR', 'LAW', 'ALB'], dnsDriverIds: [] },

  // R11 — Austrian GP — 2025-06-29
  { raceId: 'r11', classification: [
    { position: 1, driverId: 'PIA', time: '1:23:45.332', gap: 'Leader', points: 25, status: 'finished' as const },
    { position: 2, driverId: 'LEC', time: '1:23:48.189', gap: '+2.857s', points: 18, status: 'finished' as const },
    { position: 3, driverId: 'HAM', time: '1:23:51.445', gap: '+6.113s', points: 15, status: 'finished' as const },
    { position: 4, driverId: 'RUS', time: '1:23:57.998', gap: '+12.666s', points: 12, status: 'finished' as const },
    { position: 5, driverId: 'LAW', time: '1:24:10.552', gap: '+25.220s', points: 10, status: 'finished' as const },
    { position: 6, driverId: 'ALO', time: '1:24:18.974', gap: '+33.642s', points: 8, status: 'finished' as const },
    { position: 7, driverId: 'BOR', time: '1:24:24.517', gap: '+39.185s', points: 6, status: 'finished' as const },
    { position: 8, driverId: 'HUL', time: '1:24:30.776', gap: '+45.444s', points: 4, status: 'finished' as const },
    { position: 9, driverId: 'OCO', time: '1:24:--', gap: '+1 lap', points: 2, status: 'finished' as const },
    { position: 10, driverId: 'STR', time: '1:24:--', gap: '+1 lap', points: 1, status: 'finished' as const },
    { position: 11, driverId: 'DOO', time: '1:24:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 12, driverId: 'GAS', time: '1:24:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 13, driverId: 'TSU', time: '1:25:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 14, driverId: 'BEA', time: '1:25:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 15, driverId: 'NOR', time: '1:25:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 16, driverId: 'SAI', time: '1:25:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 17, driverId: 'HAD', time: '1:26:--', gap: '+3 laps', points: 0, status: 'finished' as const },
    { position: 18, driverId: 'ALB', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
    { position: 19, driverId: 'VER', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
    { position: 20, driverId: 'ANT', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
  ], fastestLapDriverId: 'PIA', dnfDriverIds: ['ALB', 'VER', 'ANT'], dnsDriverIds: [] },

  // R12 — British GP — 2025-07-06
  { raceId: 'r12', classification: [
    { position: 1, driverId: 'NOR', time: '1:23:19.562', gap: 'Leader', points: 25, status: 'finished' as const },
    { position: 2, driverId: 'PIA', time: '1:23:21.981', gap: '+2.419s', points: 18, status: 'finished' as const },
    { position: 3, driverId: 'HUL', time: '1:23:30.753', gap: '+11.191s', points: 15, status: 'finished' as const },
    { position: 4, driverId: 'HAM', time: '1:23:38.162', gap: '+18.600s', points: 12, status: 'finished' as const },
    { position: 5, driverId: 'VER', time: '1:23:41.239', gap: '+21.677s', points: 10, status: 'finished' as const },
    { position: 6, driverId: 'GAS', time: '1:23:51.342', gap: '+31.780s', points: 8, status: 'finished' as const },
    { position: 7, driverId: 'STR', time: '1:23:54.407', gap: '+34.845s', points: 6, status: 'finished' as const },
    { position: 8, driverId: 'ALB', time: '1:23:58.147', gap: '+38.585s', points: 4, status: 'finished' as const },
    { position: 9, driverId: 'ALO', time: '1:24:10.630', gap: '+51.068s', points: 2, status: 'finished' as const },
    { position: 10, driverId: 'RUS', time: '1:23:--', gap: '+1 lap', points: 1, status: 'finished' as const },
    { position: 11, driverId: 'LEC', time: '1:23:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 12, driverId: 'SAI', time: '1:23:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 13, driverId: 'TSU', time: '1:24:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 14, driverId: 'BEA', time: '1:24:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 15, driverId: 'DOO', time: '1:24:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 16, driverId: 'OCO', time: '1:24:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 17, driverId: 'ANT', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
    { position: 18, driverId: 'HAD', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
    { position: 19, driverId: 'BOR', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
    { position: 20, driverId: 'LAW', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
  ], fastestLapDriverId: 'PIA', dnfDriverIds: ['ANT', 'HAD', 'BOR', 'LAW'], dnsDriverIds: [] },

  // R13 — Belgian GP — 2025-07-27 — SPRINT
  { raceId: 'r13', classification: [
    { position: 1, driverId: 'PIA', time: '1:27:11.038', gap: 'Leader', points: 25, status: 'finished' as const },
    { position: 2, driverId: 'NOR', time: '1:27:13.942', gap: '+2.904s', points: 18, status: 'finished' as const },
    { position: 3, driverId: 'LEC', time: '1:27:15.101', gap: '+4.063s', points: 15, status: 'finished' as const },
    { position: 4, driverId: 'VER', time: '1:27:17.793', gap: '+6.755s', points: 12, status: 'finished' as const },
    { position: 5, driverId: 'RUS', time: '1:27:21.749', gap: '+10.711s', points: 10, status: 'finished' as const },
    { position: 6, driverId: 'ALB', time: '1:27:28.304', gap: '+17.266s', points: 8, status: 'finished' as const },
    { position: 7, driverId: 'HAM', time: '1:27:34.527', gap: '+23.489s', points: 6, status: 'finished' as const },
    { position: 8, driverId: 'LAW', time: '1:27:39.294', gap: '+28.256s', points: 4, status: 'finished' as const },
    { position: 9, driverId: 'BOR', time: '1:27:50.621', gap: '+39.583s', points: 2, status: 'finished' as const },
    { position: 10, driverId: 'GAS', time: '1:27:54.896', gap: '+43.858s', points: 1, status: 'finished' as const },
    { position: 11, driverId: 'SAI', time: '1:27:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 12, driverId: 'STR', time: '1:27:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 13, driverId: 'ALO', time: '1:27:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 14, driverId: 'HUL', time: '1:27:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 15, driverId: 'OCO', time: '1:27:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 16, driverId: 'TSU', time: '1:28:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 17, driverId: 'DOO', time: '1:28:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 18, driverId: 'ANT', time: '1:28:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 19, driverId: 'BEA', time: '1:28:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 20, driverId: 'HAD', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
  ], fastestLapDriverId: 'ANT', dnfDriverIds: ['HAD'], dnsDriverIds: [],
    sprintClassification: [
      { position: 1, driverId: 'VER', time: '28:20.115', gap: 'Leader', points: 8, status: 'finished' as const },
      { position: 2, driverId: 'PIA', time: '28:21.885', gap: '+1.770s', points: 7, status: 'finished' as const },
      { position: 3, driverId: 'NOR', time: '28:22.771', gap: '+2.656s', points: 6, status: 'finished' as const },
      { position: 4, driverId: 'LEC', time: '28:23.658', gap: '+3.543s', points: 5, status: 'finished' as const },
      { position: 5, driverId: 'OCO', time: '28:26.764', gap: '+6.649s', points: 4, status: 'finished' as const },
      { position: 6, driverId: 'SAI', time: '28:27.236', gap: '+7.121s', points: 3, status: 'finished' as const },
      { position: 7, driverId: 'BEA', time: '28:29.957', gap: '+9.842s', points: 2, status: 'finished' as const },
      { position: 8, driverId: 'HAD', time: '28:31.109', gap: '+10.994s', points: 1, status: 'finished' as const },
    ] },

  // R14 — Hungarian GP — 2025-08-03
  { raceId: 'r14', classification: [
    { position: 1, driverId: 'NOR', time: '1:31:48.115', gap: 'Leader', points: 25, status: 'finished' as const },
    { position: 2, driverId: 'PIA', time: '1:31:51.007', gap: '+2.892s', points: 18, status: 'finished' as const },
    { position: 3, driverId: 'RUS', time: '1:31:55.638', gap: '+7.523s', points: 15, status: 'finished' as const },
    { position: 4, driverId: 'LEC', time: '1:32:11.247', gap: '+23.132s', points: 12, status: 'finished' as const },
    { position: 5, driverId: 'ALO', time: '1:32:28.566', gap: '+40.451s', points: 10, status: 'finished' as const },
    { position: 6, driverId: 'BOR', time: '1:32:38.262', gap: '+50.147s', points: 8, status: 'finished' as const },
    { position: 7, driverId: 'STR', time: '1:32:43.553', gap: '+55.438s', points: 6, status: 'finished' as const },
    { position: 8, driverId: 'LAW', time: '1:32:59.414', gap: '+71.299s', points: 4, status: 'finished' as const },
    { position: 9, driverId: 'VER', time: '1:31:--', gap: '+1 lap', points: 2, status: 'finished' as const },
    { position: 10, driverId: 'ANT', time: '1:31:--', gap: '+1 lap', points: 1, status: 'finished' as const },
    { position: 11, driverId: 'HAD', time: '1:31:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 12, driverId: 'HUL', time: '1:31:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 13, driverId: 'ALB', time: '1:32:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 14, driverId: 'SAI', time: '1:32:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 15, driverId: 'GAS', time: '1:32:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 16, driverId: 'TSU', time: '1:32:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 17, driverId: 'DOO', time: '1:32:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 18, driverId: 'OCO', time: '1:33:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 19, driverId: 'HAM', time: '1:33:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 20, driverId: 'BEA', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
  ], fastestLapDriverId: 'RUS', dnfDriverIds: ['BEA'], dnsDriverIds: [] },

  // R15 — Dutch GP — 2025-08-31
  { raceId: 'r15', classification: [
    { position: 1, driverId: 'PIA', time: '1:30:45.129', gap: 'Leader', points: 25, status: 'finished' as const },
    { position: 2, driverId: 'VER', time: '1:30:48.450', gap: '+3.321s', points: 18, status: 'finished' as const },
    { position: 3, driverId: 'HAD', time: '1:30:57.662', gap: '+12.533s', points: 15, status: 'finished' as const },
    { position: 4, driverId: 'RUS', time: '1:31:03.224', gap: '+18.095s', points: 12, status: 'finished' as const },
    { position: 5, driverId: 'ALB', time: '1:31:07.856', gap: '+22.727s', points: 10, status: 'finished' as const },
    { position: 6, driverId: 'BEA', time: '1:31:16.823', gap: '+31.694s', points: 8, status: 'finished' as const },
    { position: 7, driverId: 'STR', time: '1:31:25.152', gap: '+40.023s', points: 6, status: 'finished' as const },
    { position: 8, driverId: 'ALO', time: '1:31:39.543', gap: '+54.414s', points: 4, status: 'finished' as const },
    { position: 9, driverId: 'TSU', time: '1:31:--', gap: '+1 lap', points: 2, status: 'finished' as const },
    { position: 10, driverId: 'OCO', time: '1:31:--', gap: '+1 lap', points: 1, status: 'finished' as const },
    { position: 11, driverId: 'LAW', time: '1:31:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 12, driverId: 'GAS', time: '1:31:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 13, driverId: 'ANT', time: '1:31:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 14, driverId: 'BOR', time: '1:31:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 15, driverId: 'DOO', time: '1:31:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 16, driverId: 'SAI', time: '1:32:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 17, driverId: 'HUL', time: '1:32:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 18, driverId: 'NOR', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
    { position: 19, driverId: 'LEC', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
    { position: 20, driverId: 'HAM', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
  ], fastestLapDriverId: 'PIA', dnfDriverIds: ['NOR', 'LEC', 'HAM'], dnsDriverIds: [] },

  // R16 — Italian GP — 2025-09-07
  { raceId: 'r16', classification: [
    { position: 1, driverId: 'NOR', time: '1:20:35.412', gap: 'Leader', points: 25, status: 'finished' as const },
    { position: 2, driverId: 'PIA', time: '1:20:37.778', gap: '+2.366s', points: 18, status: 'finished' as const },
    { position: 3, driverId: 'LEC', time: '1:20:44.923', gap: '+9.511s', points: 15, status: 'finished' as const },
    { position: 4, driverId: 'RUS', time: '1:20:50.279', gap: '+14.867s', points: 12, status: 'finished' as const },
    { position: 5, driverId: 'HAM', time: '1:21:03.225', gap: '+27.813s', points: 10, status: 'finished' as const },
    { position: 6, driverId: 'ALB', time: '1:21:09.594', gap: '+34.182s', points: 8, status: 'finished' as const },
    { position: 7, driverId: 'BOR', time: '1:21:13.325', gap: '+37.913s', points: 6, status: 'finished' as const },
    { position: 8, driverId: 'ANT', time: '1:21:14.987', gap: '+39.575s', points: 4, status: 'finished' as const },
    { position: 9, driverId: 'HAD', time: '1:21:--', gap: '+1 lap', points: 2, status: 'finished' as const },
    { position: 10, driverId: 'STR', time: '1:21:--', gap: '+1 lap', points: 1, status: 'finished' as const },
    { position: 11, driverId: 'OCO', time: '1:21:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 12, driverId: 'SAI', time: '1:21:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 13, driverId: 'TSU', time: '1:21:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 14, driverId: 'LAW', time: '1:21:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 15, driverId: 'HUL', time: '1:21:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 16, driverId: 'DOO', time: '1:22:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 17, driverId: 'GAS', time: '1:22:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 18, driverId: 'VER', time: '1:22:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 19, driverId: 'BEA', time: '1:22:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 20, driverId: 'ALO', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
  ], fastestLapDriverId: 'NOR', dnfDriverIds: ['ALO'], dnsDriverIds: [] },

  // R17 — Azerbaijan GP — 2025-09-21
  { raceId: 'r17', classification: [
    { position: 1, driverId: 'VER', time: '1:35:19.876', gap: 'Leader', points: 25, status: 'finished' as const },
    { position: 2, driverId: 'RUS', time: '1:35:22.302', gap: '+2.426s', points: 18, status: 'finished' as const },
    { position: 3, driverId: 'SAI', time: '1:35:25.808', gap: '+5.932s', points: 15, status: 'finished' as const },
    { position: 4, driverId: 'ANT', time: '1:35:29.711', gap: '+9.835s', points: 12, status: 'finished' as const },
    { position: 5, driverId: 'LAW', time: '1:35:38.238', gap: '+18.362s', points: 10, status: 'finished' as const },
    { position: 6, driverId: 'TSU', time: '1:35:43.772', gap: '+23.896s', points: 8, status: 'finished' as const },
    { position: 7, driverId: 'NOR', time: '1:35:52.090', gap: '+32.214s', points: 6, status: 'finished' as const },
    { position: 8, driverId: 'HAM', time: '1:35:55.113', gap: '+35.237s', points: 4, status: 'finished' as const },
    { position: 9, driverId: 'LEC', time: '1:35:59.352', gap: '+39.476s', points: 2, status: 'finished' as const },
    { position: 10, driverId: 'HAD', time: '1:36:14.789', gap: '+54.913s', points: 1, status: 'finished' as const },
    { position: 11, driverId: 'ALB', time: '1:35:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 12, driverId: 'ALO', time: '1:35:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 13, driverId: 'HUL', time: '1:35:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 14, driverId: 'DOO', time: '1:35:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 15, driverId: 'BOR', time: '1:35:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 16, driverId: 'OCO', time: '1:36:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 17, driverId: 'STR', time: '1:36:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 18, driverId: 'GAS', time: '1:36:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 19, driverId: 'BEA', time: '1:36:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 20, driverId: 'PIA', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
  ], fastestLapDriverId: 'VER', dnfDriverIds: ['PIA'], dnsDriverIds: [] },

  // R18 — Singapore GP — 2025-10-05
  { raceId: 'r18', classification: [
    { position: 1, driverId: 'RUS', time: '2:05:22.178', gap: 'Leader', points: 25, status: 'finished' as const },
    { position: 2, driverId: 'VER', time: '2:05:26.452', gap: '+4.274s', points: 18, status: 'finished' as const },
    { position: 3, driverId: 'NOR', time: '2:05:30.124', gap: '+7.946s', points: 15, status: 'finished' as const },
    { position: 4, driverId: 'PIA', time: '2:05:34.555', gap: '+12.377s', points: 12, status: 'finished' as const },
    { position: 5, driverId: 'ANT', time: '2:05:42.876', gap: '+20.698s', points: 10, status: 'finished' as const },
    { position: 6, driverId: 'LEC', time: '2:05:53.340', gap: '+31.162s', points: 8, status: 'finished' as const },
    { position: 7, driverId: 'ALO', time: '2:06:04.521', gap: '+42.343s', points: 6, status: 'finished' as const },
    { position: 8, driverId: 'HAM', time: '2:06:10.781', gap: '+48.603s', points: 4, status: 'finished' as const },
    { position: 9, driverId: 'BEA', time: '2:06:30.337', gap: '+68.159s', points: 2, status: 'finished' as const },
    { position: 10, driverId: 'SAI', time: '2:05:--', gap: '+1 lap', points: 1, status: 'finished' as const },
    { position: 11, driverId: 'OCO', time: '2:05:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 12, driverId: 'STR', time: '2:05:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 13, driverId: 'HUL', time: '2:05:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 14, driverId: 'LAW', time: '2:06:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 15, driverId: 'BOR', time: '2:06:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 16, driverId: 'TSU', time: '2:06:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 17, driverId: 'DOO', time: '2:06:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 18, driverId: 'HAD', time: '2:06:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 19, driverId: 'GAS', time: '2:06:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 20, driverId: 'ALB', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
  ], fastestLapDriverId: 'HAM', dnfDriverIds: ['ALB'], dnsDriverIds: [] },

  // R19 — United States GP — 2025-10-19 — SPRINT
  { raceId: 'r19', classification: [
    { position: 1, driverId: 'VER', time: '1:34:18.762', gap: 'Leader', points: 25, status: 'finished' as const },
    { position: 2, driverId: 'NOR', time: '1:34:21.235', gap: '+2.473s', points: 18, status: 'finished' as const },
    { position: 3, driverId: 'LEC', time: '1:34:27.673', gap: '+8.911s', points: 15, status: 'finished' as const },
    { position: 4, driverId: 'HAM', time: '1:34:33.415', gap: '+14.653s', points: 12, status: 'finished' as const },
    { position: 5, driverId: 'PIA', time: '1:34:44.321', gap: '+25.559s', points: 10, status: 'finished' as const },
    { position: 6, driverId: 'RUS', time: '1:34:56.780', gap: '+38.018s', points: 8, status: 'finished' as const },
    { position: 7, driverId: 'TSU', time: '1:35:07.419', gap: '+48.657s', points: 6, status: 'finished' as const },
    { position: 8, driverId: 'HUL', time: '1:35:14.227', gap: '+55.465s', points: 4, status: 'finished' as const },
    { position: 9, driverId: 'BEA', time: '1:35:--', gap: '+1 lap', points: 2, status: 'finished' as const },
    { position: 10, driverId: 'ALO', time: '1:35:--', gap: '+1 lap', points: 1, status: 'finished' as const },
    { position: 11, driverId: 'ALB', time: '1:35:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 12, driverId: 'LAW', time: '1:35:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 13, driverId: 'STR', time: '1:35:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 14, driverId: 'OCO', time: '1:35:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 15, driverId: 'HAD', time: '1:35:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 16, driverId: 'GAS', time: '1:35:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 17, driverId: 'BOR', time: '1:36:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 18, driverId: 'DOO', time: '1:36:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 19, driverId: 'ANT', time: '1:36:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 20, driverId: 'SAI', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
  ], fastestLapDriverId: 'ANT', dnfDriverIds: ['SAI'], dnsDriverIds: [],
    sprintClassification: [
      { position: 1, driverId: 'VER', time: '31:08.456', gap: 'Leader', points: 8, status: 'finished' as const },
      { position: 2, driverId: 'RUS', time: '31:10.187', gap: '+1.731s', points: 7, status: 'finished' as const },
      { position: 3, driverId: 'SAI', time: '31:11.705', gap: '+3.249s', points: 6, status: 'finished' as const },
      { position: 4, driverId: 'HAM', time: '31:13.221', gap: '+4.765s', points: 5, status: 'finished' as const },
      { position: 5, driverId: 'LEC', time: '31:14.743', gap: '+6.287s', points: 4, status: 'finished' as const },
      { position: 6, driverId: 'ALB', time: '31:17.366', gap: '+8.910s', points: 3, status: 'finished' as const },
      { position: 7, driverId: 'TSU', time: '31:18.502', gap: '+10.046s', points: 2, status: 'finished' as const },
      { position: 8, driverId: 'ANT', time: '31:19.187', gap: '+10.731s', points: 1, status: 'finished' as const },
    ] },

  // R20 — Mexico City GP — 2025-10-26
  { raceId: 'r20', classification: [
    { position: 1, driverId: 'NOR', time: '1:41:02.119', gap: 'Leader', points: 25, status: 'finished' as const },
    { position: 2, driverId: 'LEC', time: '1:41:06.783', gap: '+4.664s', points: 18, status: 'finished' as const },
    { position: 3, driverId: 'VER', time: '1:41:09.025', gap: '+6.906s', points: 15, status: 'finished' as const },
    { position: 4, driverId: 'BEA', time: '1:41:26.347', gap: '+24.228s', points: 12, status: 'finished' as const },
    { position: 5, driverId: 'PIA', time: '1:41:29.433', gap: '+27.314s', points: 10, status: 'finished' as const },
    { position: 6, driverId: 'ANT', time: '1:41:33.213', gap: '+31.094s', points: 8, status: 'finished' as const },
    { position: 7, driverId: 'RUS', time: '1:41:45.226', gap: '+43.107s', points: 6, status: 'finished' as const },
    { position: 8, driverId: 'HAM', time: '1:41:49.114', gap: '+46.995s', points: 4, status: 'finished' as const },
    { position: 9, driverId: 'OCO', time: '1:42:02.563', gap: '+60.444s', points: 2, status: 'finished' as const },
    { position: 10, driverId: 'BOR', time: '1:42:--', gap: '+1 lap', points: 1, status: 'finished' as const },
    { position: 11, driverId: 'HUL', time: '1:42:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 12, driverId: 'ALB', time: '1:42:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 13, driverId: 'TSU', time: '1:42:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 14, driverId: 'STR', time: '1:42:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 15, driverId: 'GAS', time: '1:42:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 16, driverId: 'DOO', time: '1:42:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 17, driverId: 'HAD', time: '1:43:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 18, driverId: 'SAI', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
    { position: 19, driverId: 'ALO', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
    { position: 20, driverId: 'LAW', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
  ], fastestLapDriverId: 'RUS', dnfDriverIds: ['SAI', 'ALO', 'LAW'], dnsDriverIds: [] },

  // R21 — São Paulo GP — 2025-11-09 — SPRINT
  { raceId: 'r21', classification: [
    { position: 1, driverId: 'ANT', time: '1:33:26.514', gap: 'Leader', points: 25, status: 'finished' as const },
    { position: 2, driverId: 'VER', time: '1:33:29.832', gap: '+3.318s', points: 18, status: 'finished' as const },
    { position: 3, driverId: 'RUS', time: '1:33:32.167', gap: '+5.653s', points: 15, status: 'finished' as const },
    { position: 4, driverId: 'PIA', time: '1:33:35.489', gap: '+8.975s', points: 12, status: 'finished' as const },
    { position: 5, driverId: 'BEA', time: '1:33:42.227', gap: '+15.713s', points: 10, status: 'finished' as const },
    { position: 6, driverId: 'LAW', time: '1:33:47.891', gap: '+21.377s', points: 8, status: 'finished' as const },
    { position: 7, driverId: 'HAD', time: '1:33:51.732', gap: '+25.218s', points: 6, status: 'finished' as const },
    { position: 8, driverId: 'HUL', time: '1:33:58.049', gap: '+31.535s', points: 4, status: 'finished' as const },
    { position: 9, driverId: 'GAS', time: '1:34:--', gap: '+1 lap', points: 2, status: 'finished' as const },
    { position: 10, driverId: 'OCO', time: '1:34:--', gap: '+1 lap', points: 1, status: 'finished' as const },
    { position: 11, driverId: 'STR', time: '1:34:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 12, driverId: 'DOO', time: '1:34:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 13, driverId: 'ALB', time: '1:34:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 14, driverId: 'TSU', time: '1:34:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 15, driverId: 'SAI', time: '1:34:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 16, driverId: 'ALO', time: '1:35:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 17, driverId: 'NOR', time: '1:35:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 18, driverId: 'HAM', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
    { position: 19, driverId: 'LEC', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
    { position: 20, driverId: 'BOR', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
  ], fastestLapDriverId: 'ALB', dnfDriverIds: ['HAM', 'LEC', 'BOR'], dnsDriverIds: [],
    sprintClassification: [
      { position: 1, driverId: 'NOR', time: '30:11.567', gap: 'Leader', points: 8, status: 'finished' as const },
      { position: 2, driverId: 'ANT', time: '30:13.108', gap: '+1.541s', points: 7, status: 'finished' as const },
      { position: 3, driverId: 'RUS', time: '30:14.876', gap: '+3.309s', points: 6, status: 'finished' as const },
      { position: 4, driverId: 'VER', time: '30:16.542', gap: '+4.975s', points: 5, status: 'finished' as const },
      { position: 5, driverId: 'LEC', time: '30:18.291', gap: '+6.724s', points: 4, status: 'finished' as const },
      { position: 6, driverId: 'ALO', time: '30:20.905', gap: '+9.338s', points: 3, status: 'finished' as const },
      { position: 7, driverId: 'HAM', time: '30:22.778', gap: '+11.211s', points: 2, status: 'finished' as const },
      { position: 8, driverId: 'GAS', time: '30:24.449', gap: '+12.882s', points: 1, status: 'finished' as const },
    ] },

  // R22 — Las Vegas GP — 2025-11-23
  { raceId: 'r22', classification: [
    { position: 1, driverId: 'VER', time: '1:30:11.856', gap: 'Leader', points: 25, status: 'finished' as const },
    { position: 2, driverId: 'RUS', time: '1:30:14.723', gap: '+2.867s', points: 18, status: 'finished' as const },
    { position: 3, driverId: 'ANT', time: '1:30:17.451', gap: '+5.595s', points: 15, status: 'finished' as const },
    { position: 4, driverId: 'LEC', time: '1:30:20.978', gap: '+9.122s', points: 12, status: 'finished' as const },
    { position: 5, driverId: 'SAI', time: '1:30:26.334', gap: '+14.478s', points: 10, status: 'finished' as const },
    { position: 6, driverId: 'HAD', time: '1:30:30.557', gap: '+18.701s', points: 8, status: 'finished' as const },
    { position: 7, driverId: 'HUL', time: '1:30:33.889', gap: '+22.033s', points: 6, status: 'finished' as const },
    { position: 8, driverId: 'HAM', time: '1:30:38.621', gap: '+26.765s', points: 4, status: 'finished' as const },
    { position: 9, driverId: 'OCO', time: '1:30:48.719', gap: '+36.863s', points: 2, status: 'finished' as const },
    { position: 10, driverId: 'BEA', time: '1:31:--', gap: '+1 lap', points: 1, status: 'finished' as const },
    { position: 11, driverId: 'LAW', time: '1:31:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 12, driverId: 'DOO', time: '1:31:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 13, driverId: 'GAS', time: '1:31:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 14, driverId: 'TSU', time: '1:31:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 15, driverId: 'PIA', time: '1:31:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 16, driverId: 'NOR', time: '1:32:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 17, driverId: 'ALB', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
    { position: 18, driverId: 'BOR', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
    { position: 19, driverId: 'STR', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
    { position: 20, driverId: 'ALO', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
  ], fastestLapDriverId: 'VER', dnfDriverIds: ['ALB', 'BOR', 'STR', 'ALO'], dnsDriverIds: [] },

  // R23 — Qatar GP — 2025-11-30
  { raceId: 'r23', classification: [
    { position: 1, driverId: 'VER', time: '1:28:30.221', gap: 'Leader', points: 25, status: 'finished' as const },
    { position: 2, driverId: 'PIA', time: '1:28:32.478', gap: '+2.257s', points: 18, status: 'finished' as const },
    { position: 3, driverId: 'SAI', time: '1:28:35.309', gap: '+5.088s', points: 15, status: 'finished' as const },
    { position: 4, driverId: 'NOR', time: '1:28:38.776', gap: '+8.555s', points: 12, status: 'finished' as const },
    { position: 5, driverId: 'ANT', time: '1:28:46.441', gap: '+16.220s', points: 10, status: 'finished' as const },
    { position: 6, driverId: 'RUS', time: '1:28:51.147', gap: '+20.926s', points: 8, status: 'finished' as const },
    { position: 7, driverId: 'ALO', time: '1:28:58.755', gap: '+28.534s', points: 6, status: 'finished' as const },
    { position: 8, driverId: 'LEC', time: '1:29:09.873', gap: '+39.652s', points: 4, status: 'finished' as const },
    { position: 9, driverId: 'LAW', time: '1:29:--', gap: '+1 lap', points: 2, status: 'finished' as const },
    { position: 10, driverId: 'TSU', time: '1:29:--', gap: '+1 lap', points: 1, status: 'finished' as const },
    { position: 11, driverId: 'ALB', time: '1:29:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 12, driverId: 'OCO', time: '1:29:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 13, driverId: 'GAS', time: '1:29:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 14, driverId: 'HAM', time: '1:29:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 15, driverId: 'DOO', time: '1:30:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 16, driverId: 'STR', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
    { position: 17, driverId: 'HAD', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
    { position: 18, driverId: 'BEA', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
    { position: 19, driverId: 'HUL', time: '', gap: 'DNF', points: 0, status: 'dnf' as const },
  ], fastestLapDriverId: 'PIA', dnfDriverIds: ['STR', 'HAD', 'BEA', 'HUL'], dnsDriverIds: [] },

  // R24 — Abu Dhabi GP — 2025-12-07
  { raceId: 'r24', classification: [
    { position: 1, driverId: 'VER', time: '1:33:59.606', gap: 'Leader', points: 25, status: 'finished' as const },
    { position: 2, driverId: 'PIA', time: '1:34:01.984', gap: '+2.378s', points: 18, status: 'finished' as const },
    { position: 3, driverId: 'NOR', time: '1:34:04.167', gap: '+4.561s', points: 15, status: 'finished' as const },
    { position: 4, driverId: 'LEC', time: '1:34:09.801', gap: '+10.195s', points: 12, status: 'finished' as const },
    { position: 5, driverId: 'RUS', time: '1:34:19.742', gap: '+20.136s', points: 10, status: 'finished' as const },
    { position: 6, driverId: 'ALO', time: '1:34:26.132', gap: '+26.526s', points: 8, status: 'finished' as const },
    { position: 7, driverId: 'OCO', time: '1:34:31.517', gap: '+31.911s', points: 6, status: 'finished' as const },
    { position: 8, driverId: 'HAM', time: '1:34:41.670', gap: '+42.064s', points: 4, status: 'finished' as const },
    { position: 9, driverId: 'HUL', time: '1:34:50.834', gap: '+51.228s', points: 2, status: 'finished' as const },
    { position: 10, driverId: 'STR', time: '1:35:--', gap: '+1 lap', points: 1, status: 'finished' as const },
    { position: 11, driverId: 'ALB', time: '1:35:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 12, driverId: 'BEA', time: '1:35:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 13, driverId: 'GAS', time: '1:35:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 14, driverId: 'BOR', time: '1:35:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 15, driverId: 'LAW', time: '1:35:--', gap: '+1 lap', points: 0, status: 'finished' as const },
    { position: 16, driverId: 'DOO', time: '1:36:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 17, driverId: 'TSU', time: '1:36:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 18, driverId: 'HAD', time: '1:36:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 19, driverId: 'ANT', time: '1:36:--', gap: '+2 laps', points: 0, status: 'finished' as const },
    { position: 20, driverId: 'SAI', time: '1:37:--', gap: '+3 laps', points: 0, status: 'finished' as const },
  ], fastestLapDriverId: 'LEC', dnfDriverIds: [], dnsDriverIds: [] },
];

export function getTeamById(id: string): Team | undefined {
  return TEAMS.find((t) => t.id === id);
}

export function getDriverById(id: string): Driver | undefined {
  return DRIVERS.find((d) => d.id === id);
}

export function getNextRace(): Race | undefined {
  return [...RACES]
    .filter((race) => race.status === 'upcoming')
    .sort((a, b) => {
      const aTime = new Date(`${a.raceDate}T${a.raceTime}:00Z`).getTime();
      const bTime = new Date(`${b.raceDate}T${b.raceTime}:00Z`).getTime();

      return aTime - bTime;
    })[0];
}

export function getRaceById(id: string): Race | undefined {
  return RACES.find((r) => r.id === id);
}