import { Team, Driver, Race, RaceResult } from '@/types';

export const TEAMS: Team[] = [
  { id: 'mercedes', name: 'Mercedes-AMG', color: '#27F4D2', shortName: 'MER' },
  { id: 'ferrari', name: 'Scuderia Ferrari', color: '#E8002D', shortName: 'FER' },
  { id: 'mclaren', name: 'McLaren', color: '#FF8000', shortName: 'MCL' },
  { id: 'red-bull', name: 'Red Bull Racing', color: '#3671C6', shortName: 'RBR' },
  { id: 'alpine', name: 'Alpine F1 Team', color: '#FF87BC', shortName: 'ALP' },
  { id: 'haas', name: 'Haas F1 Team', color: '#B6BABD', shortName: 'HAA' },
  { id: 'racing-bulls', name: 'RB F1 Team', color: '#6692FF', shortName: 'RB' },
  { id: 'williams', name: 'Williams', color: '#64C4FF', shortName: 'WIL' },
  { id: 'aston-martin', name: 'Aston Martin', color: '#229971', shortName: 'AMR' },
  { id: 'audi', name: 'Audi', color: '#D5001C', shortName: 'AUD' },
  { id: 'cadillac', name: 'Cadillac F1 Team', color: '#11457E', shortName: 'CAD' },
];

/**
 * 2026 FIA Formula One World Championship — driver standings.
 * Sourced from Jolpica/Ergast API and verified against formula1.com.
 *
 * Standings reflect completed races R01–R07 as of 2026-06-16.
 */
export const DRIVERS: Driver[] = [
  { id: 'ANT', name: 'Kimi Antonelli', shortName: 'ANT', number: 12, teamId: 'mercedes', championshipPoints: 156 },
  { id: 'HAM', name: 'Lewis Hamilton', shortName: 'HAM', number: 44, teamId: 'ferrari', championshipPoints: 115 },
  { id: 'RUS', name: 'George Russell', shortName: 'RUS', number: 63, teamId: 'mercedes', championshipPoints: 106 },
  { id: 'LEC', name: 'Charles Leclerc', shortName: 'LEC', number: 16, teamId: 'ferrari', championshipPoints: 75 },
  { id: 'NOR', name: 'Lando Norris', shortName: 'NOR', number: 4, teamId: 'mclaren', championshipPoints: 73 },
  { id: 'PIA', name: 'Oscar Piastri', shortName: 'PIA', number: 81, teamId: 'mclaren', championshipPoints: 68 },
  { id: 'VER', name: 'Max Verstappen', shortName: 'VER', number: 1, teamId: 'red-bull', championshipPoints: 55 },
  { id: 'GAS', name: 'Pierre Gasly', shortName: 'GAS', number: 10, teamId: 'alpine', championshipPoints: 41 },
  { id: 'HAD', name: 'Isack Hadjar', shortName: 'HAD', number: 6, teamId: 'red-bull', championshipPoints: 34 },
  { id: 'LAW', name: 'Liam Lawson', shortName: 'LAW', number: 30, teamId: 'racing-bulls', championshipPoints: 28 },
  { id: 'BEA', name: 'Oliver Bearman', shortName: 'BEA', number: 87, teamId: 'haas', championshipPoints: 18 },
  { id: 'COL', name: 'Franco Colapinto', shortName: 'COL', number: 43, teamId: 'alpine', championshipPoints: 16 },
  { id: 'LIN', name: 'Arvid Lindblad', shortName: 'LIN', number: 41, teamId: 'racing-bulls', championshipPoints: 13 },
  { id: 'SAI', name: 'Carlos Sainz', shortName: 'SAI', number: 55, teamId: 'williams', championshipPoints: 6 },
  { id: 'ALB', name: 'Alexander Albon', shortName: 'ALB', number: 23, teamId: 'williams', championshipPoints: 5 },
  { id: 'OCO', name: 'Esteban Ocon', shortName: 'OCO', number: 31, teamId: 'haas', championshipPoints: 3 },
  { id: 'BOR', name: 'Gabriel Bortoleto', shortName: 'BOR', number: 5, teamId: 'audi', championshipPoints: 2 },
  { id: 'ALO', name: 'Fernando Alonso', shortName: 'ALO', number: 14, teamId: 'aston-martin', championshipPoints: 1 },
  { id: 'HUL', name: 'Nico Hulkenberg', shortName: 'HUL', number: 27, teamId: 'audi', championshipPoints: 0 },
  { id: 'BOT', name: 'Valtteri Bottas', shortName: 'BOT', number: 77, teamId: 'cadillac', championshipPoints: 0 },
  { id: 'PER', name: 'Sergio Perez', shortName: 'PER', number: 11, teamId: 'cadillac', championshipPoints: 0 },
  { id: 'STR', name: 'Lance Stroll', shortName: 'STR', number: 18, teamId: 'aston-martin', championshipPoints: 0 },
];

/**
 * 2026 FIA Formula One World Championship calendar.
 * Dates and sprint flags verified against formula1.com and Jolpica/Ergast API.
 *
 * Six sprint weekends in 2026: China, Miami, Canada, Britain, Netherlands, Singapore.
 */
export const RACES: Race[] = [
  { id: 'r01', round: 1,  name: 'Australian Grand Prix',      location: 'Melbourne',        country: 'Australia',       countryFlag: '', raceDate: '2026-03-08', raceTime: '04:00', status: 'completed', hasSprint: false, winner: 'RUS', totalLaps: 58 },
  { id: 'r02', round: 2,  name: 'Chinese Grand Prix',          location: 'Shanghai',         country: 'China',           countryFlag: '', raceDate: '2026-03-15', raceTime: '07:00', status: 'completed', hasSprint: true,  sprintDate: '2026-03-14', sprintTime: '07:00', winner: 'ANT', totalLaps: 56 },
  { id: 'r03', round: 3,  name: 'Japanese Grand Prix',         location: 'Suzuka',           country: 'Japan',           countryFlag: '', raceDate: '2026-03-29', raceTime: '05:00', status: 'completed', hasSprint: false, winner: 'ANT', totalLaps: 53 },
  { id: 'r04', round: 4,  name: 'Miami Grand Prix',            location: 'Miami',            country: 'USA',             countryFlag: '', raceDate: '2026-05-03', raceTime: '20:00', status: 'completed', hasSprint: true,  sprintDate: '2026-05-02', sprintTime: '20:00', winner: 'ANT', totalLaps: 57 },
  { id: 'r05', round: 5,  name: 'Canadian Grand Prix',         location: 'Montreal',         country: 'Canada',          countryFlag: '', raceDate: '2026-05-24', raceTime: '18:00', status: 'completed', hasSprint: true,  sprintDate: '2026-05-23', sprintTime: '18:00', winner: 'ANT', totalLaps: 70 },
  { id: 'r06', round: 6,  name: 'Monaco Grand Prix',           location: 'Monte Carlo',      country: 'Monaco',          countryFlag: '', raceDate: '2026-06-07', raceTime: '13:00', status: 'completed', hasSprint: false, winner: 'ANT', totalLaps: 78 },
  { id: 'r07', round: 7,  name: 'Barcelona Grand Prix',        location: 'Barcelona',        country: 'Spain',           countryFlag: '', raceDate: '2026-06-14', raceTime: '13:00', status: 'completed', hasSprint: false, winner: 'HAM', totalLaps: 66 },
  { id: 'r08', round: 8,  name: 'Austrian Grand Prix',         location: 'Spielberg',        country: 'Austria',         countryFlag: '', raceDate: '2026-06-28', raceTime: '13:00', status: 'upcoming',  hasSprint: false, totalLaps: 71 },
  { id: 'r09', round: 9,  name: 'British Grand Prix',          location: 'Silverstone',      country: 'United Kingdom',  countryFlag: '', raceDate: '2026-07-05', raceTime: '14:00', status: 'upcoming',  hasSprint: true,  sprintDate: '2026-07-04', sprintTime: '14:00', totalLaps: 52 },
  { id: 'r10', round: 10, name: 'Belgian Grand Prix',          location: 'Spa-Francorchamps', country: 'Belgium',        countryFlag: '', raceDate: '2026-07-19', raceTime: '13:00', status: 'upcoming',  hasSprint: false, totalLaps: 44 },
  { id: 'r11', round: 11, name: 'Hungarian Grand Prix',        location: 'Budapest',         country: 'Hungary',         countryFlag: '', raceDate: '2026-07-26', raceTime: '13:00', status: 'upcoming',  hasSprint: false, totalLaps: 70 },
  { id: 'r12', round: 12, name: 'Dutch Grand Prix',            location: 'Zandvoort',        country: 'Netherlands',     countryFlag: '', raceDate: '2026-08-23', raceTime: '13:00', status: 'upcoming',  hasSprint: true,  sprintDate: '2026-08-22', sprintTime: '13:00', totalLaps: 72 },
  { id: 'r13', round: 13, name: 'Italian Grand Prix',          location: 'Monza',            country: 'Italy',           countryFlag: '', raceDate: '2026-09-06', raceTime: '13:00', status: 'upcoming',  hasSprint: false, totalLaps: 53 },
  { id: 'r14', round: 14, name: 'Spanish Grand Prix',          location: 'Madrid',           country: 'Spain',           countryFlag: '', raceDate: '2026-09-13', raceTime: '13:00', status: 'upcoming',  hasSprint: false, totalLaps: 66 },
  { id: 'r15', round: 15, name: 'Azerbaijan Grand Prix',       location: 'Baku',             country: 'Azerbaijan',      countryFlag: '', raceDate: '2026-09-26', raceTime: '12:00', status: 'upcoming',  hasSprint: false, totalLaps: 51 },
  { id: 'r16', round: 16, name: 'Singapore Grand Prix',        location: 'Marina Bay',       country: 'Singapore',       countryFlag: '', raceDate: '2026-10-11', raceTime: '12:00', status: 'upcoming',  hasSprint: true,  sprintDate: '2026-10-10', sprintTime: '12:00', totalLaps: 62 },
  { id: 'r17', round: 17, name: 'United States Grand Prix',    location: 'Austin',           country: 'USA',             countryFlag: '', raceDate: '2026-10-25', raceTime: '19:00', status: 'upcoming',  hasSprint: false, totalLaps: 56 },
  { id: 'r18', round: 18, name: 'Mexico City Grand Prix',      location: 'Mexico City',      country: 'Mexico',          countryFlag: '', raceDate: '2026-11-01', raceTime: '20:00', status: 'upcoming',  hasSprint: false, totalLaps: 71 },
  { id: 'r19', round: 19, name: 'Brazilian Grand Prix',        location: 'Interlagos',       country: 'Brazil',          countryFlag: '', raceDate: '2026-11-08', raceTime: '17:00', status: 'upcoming',  hasSprint: false, totalLaps: 71 },
  { id: 'r20', round: 20, name: 'Las Vegas Grand Prix',        location: 'Las Vegas',        country: 'USA',             countryFlag: '', raceDate: '2026-11-22', raceTime: '06:00', status: 'upcoming',  hasSprint: false, totalLaps: 50 },
  { id: 'r21', round: 21, name: 'Qatar Grand Prix',            location: 'Lusail',           country: 'Qatar',           countryFlag: '', raceDate: '2026-11-29', raceTime: '17:00', status: 'upcoming',  hasSprint: false, totalLaps: 57 },
  { id: 'r22', round: 22, name: 'Abu Dhabi Grand Prix',        location: 'Yas Marina',       country: 'UAE',             countryFlag: '', raceDate: '2026-12-06', raceTime: '14:00', status: 'upcoming',  hasSprint: false, totalLaps: 58 },
];

/**
 * 2026 FIA Formula One World Championship — verified race results.
 * Sourced from Jolpica/Ergast API and cross-checked against formula1.com.
 *
 * Used as fallback when the live API doesn't return data.
 * The live Jolpica API is the authoritative source — this data fills gaps.
 */
export const MOCK_RACE_RESULTS: RaceResult[] = [
  // ── R01 — Australian GP — 2026-03-08 ────────────────────────────────────
  {
    raceId: 'r01',
    classification: [
      { position: 1,  driverId: 'RUS', time: '1:23:06.801', gap: 'Leader',    points: 25, status: 'finished' as const },
      { position: 2,  driverId: 'ANT', time: '1:23:09.775', gap: '+2.974s',   points: 18, status: 'finished' as const },
      { position: 3,  driverId: 'LEC', time: '1:23:22.320', gap: '+15.519s',  points: 15, status: 'finished' as const },
      { position: 4,  driverId: 'HAM', time: '1:23:25.801', gap: '+19.000s',  points: 12, status: 'finished' as const },
      { position: 5,  driverId: 'NOR', time: '1:23:28.200', gap: '+21.399s',  points: 10, status: 'finished' as const },
      { position: 6,  driverId: 'VER', time: '1:23:31.500', gap: '+24.699s',  points: 8,  status: 'finished' as const },
      { position: 7,  driverId: 'BEA', time: '+1 lap',       gap: '+1 lap',    points: 6,  status: 'finished' as const },
      { position: 8,  driverId: 'LIN', time: '+1 lap',       gap: '+1 lap',    points: 4,  status: 'finished' as const },
      { position: 9,  driverId: 'BOR', time: '+1 lap',       gap: '+1 lap',    points: 2,  status: 'finished' as const },
      { position: 10, driverId: 'GAS', time: '+1 lap',       gap: '+1 lap',    points: 1,  status: 'finished' as const },
      { position: 11, driverId: 'OCO', time: '+1 lap',       gap: '+1 lap',    points: 0,  status: 'finished' as const },
      { position: 12, driverId: 'ALB', time: '+1 lap',       gap: '+1 lap',    points: 0,  status: 'finished' as const },
      { position: 13, driverId: 'LAW', time: '+1 lap',       gap: '+1 lap',    points: 0,  status: 'finished' as const },
      { position: 14, driverId: 'COL', time: '+1 lap',       gap: '+1 lap',    points: 0,  status: 'finished' as const },
      { position: 15, driverId: 'SAI', time: '+1 lap',       gap: '+1 lap',    points: 0,  status: 'finished' as const },
      { position: 16, driverId: 'PER', time: '+1 lap',       gap: '+1 lap',    points: 0,  status: 'finished' as const },
      { position: 17, driverId: 'STR', time: '+1 lap',       gap: '+1 lap',    points: 0,  status: 'finished' as const },
      { position: 18, driverId: 'ALO', time: '',              gap: 'DNF',       points: 0,  status: 'dnf' as const },
      { position: 19, driverId: 'BOT', time: '',              gap: 'DNF',       points: 0,  status: 'dnf' as const },
      { position: 20, driverId: 'HAD', time: '',              gap: 'DNF',       points: 0,  status: 'dnf' as const },
      { position: 21, driverId: 'PIA', time: '',              gap: 'DNS',       points: 0,  status: 'dns' as const },
      { position: 22, driverId: 'HUL', time: '',              gap: 'DNS',       points: 0,  status: 'dns' as const },
    ],
    fastestLapDriverId: 'VER',
    dnfDriverIds: ['ALO', 'BOT', 'HAD'],
    dnsDriverIds: ['PIA', 'HUL'],
  },

  // ── R02 — Chinese GP — 2026-03-15 — SPRINT ──────────────────────────────
  {
    raceId: 'r02',
    classification: [
      { position: 1,  driverId: 'ANT', time: '1:33:15.607', gap: 'Leader',    points: 25, status: 'finished' as const },
      { position: 2,  driverId: 'RUS', time: '1:33:21.122', gap: '+5.515s',   points: 18, status: 'finished' as const },
      { position: 3,  driverId: 'HAM', time: '1:33:40.874', gap: '+25.267s',  points: 15, status: 'finished' as const },
      { position: 4,  driverId: 'LEC', time: '1:33:45.100', gap: '+29.493s',  points: 12, status: 'finished' as const },
      { position: 5,  driverId: 'BEA', time: '1:33:50.200', gap: '+34.593s',  points: 10, status: 'finished' as const },
      { position: 6,  driverId: 'GAS', time: '1:33:55.000', gap: '+39.393s',  points: 8,  status: 'finished' as const },
      { position: 7,  driverId: 'LAW', time: '1:34:00.100', gap: '+44.493s',  points: 6,  status: 'finished' as const },
      { position: 8,  driverId: 'HAD', time: '1:34:05.200', gap: '+49.593s',  points: 4,  status: 'finished' as const },
      { position: 9,  driverId: 'SAI', time: '+1 lap',       gap: '+1 lap',    points: 2,  status: 'finished' as const },
      { position: 10, driverId: 'COL', time: '+1 lap',       gap: '+1 lap',    points: 1,  status: 'finished' as const },
      { position: 11, driverId: 'HUL', time: '+1 lap',       gap: '+1 lap',    points: 0,  status: 'finished' as const },
      { position: 12, driverId: 'LIN', time: '+1 lap',       gap: '+1 lap',    points: 0,  status: 'finished' as const },
      { position: 13, driverId: 'BOT', time: '+1 lap',       gap: '+1 lap',    points: 0,  status: 'finished' as const },
      { position: 14, driverId: 'OCO', time: '+1 lap',       gap: '+1 lap',    points: 0,  status: 'finished' as const },
      { position: 15, driverId: 'PER', time: '+1 lap',       gap: '+1 lap',    points: 0,  status: 'finished' as const },
      { position: 16, driverId: 'VER', time: '',              gap: 'DNF',       points: 0,  status: 'dnf' as const },
      { position: 17, driverId: 'ALO', time: '',              gap: 'DNF',       points: 0,  status: 'dnf' as const },
      { position: 18, driverId: 'STR', time: '',              gap: 'DNF',       points: 0,  status: 'dnf' as const },
      { position: 19, driverId: 'PIA', time: '',              gap: 'DNS',       points: 0,  status: 'dns' as const },
      { position: 20, driverId: 'NOR', time: '',              gap: 'DNS',       points: 0,  status: 'dns' as const },
      { position: 21, driverId: 'BOR', time: '',              gap: 'DNS',       points: 0,  status: 'dns' as const },
      { position: 22, driverId: 'ALB', time: '',              gap: 'DNS',       points: 0,  status: 'dns' as const },
    ],
    fastestLapDriverId: 'ANT',
    dnfDriverIds: ['VER', 'ALO', 'STR'],
    dnsDriverIds: ['PIA', 'NOR', 'BOR', 'ALB'],
    sprintClassification: [
      { position: 1, driverId: 'RUS', time: '—', gap: 'Leader',   points: 8, status: 'finished' as const },
      { position: 2, driverId: 'LEC', time: '—', gap: '—',         points: 7, status: 'finished' as const },
      { position: 3, driverId: 'HAM', time: '—', gap: '—',         points: 6, status: 'finished' as const },
      { position: 4, driverId: 'NOR', time: '—', gap: '—',         points: 5, status: 'finished' as const },
      { position: 5, driverId: 'ANT', time: '—', gap: '—',         points: 4, status: 'finished' as const },
      { position: 6, driverId: 'PIA', time: '—', gap: '—',         points: 3, status: 'finished' as const },
      { position: 7, driverId: 'LAW', time: '—', gap: '—',         points: 2, status: 'finished' as const },
      { position: 8, driverId: 'BEA', time: '—', gap: '—',         points: 1, status: 'finished' as const },
    ],
  },

  // ── R03 — Japanese GP — 2026-03-29 ──────────────────────────────────────
  {
    raceId: 'r03',
    classification: [
      { position: 1,  driverId: 'ANT', time: '1:28:03.403', gap: 'Leader',   points: 25, status: 'finished' as const },
      { position: 2,  driverId: 'PIA', time: '1:28:17.125', gap: '+13.722s',  points: 18, status: 'finished' as const },
      { position: 3,  driverId: 'LEC', time: '1:28:18.673', gap: '+15.270s',  points: 15, status: 'finished' as const },
      { position: 4,  driverId: 'RUS', time: '1:28:25.000', gap: '+21.597s',  points: 12, status: 'finished' as const },
      { position: 5,  driverId: 'NOR', time: '1:28:30.100', gap: '+26.697s',  points: 10, status: 'finished' as const },
      { position: 6,  driverId: 'HAM', time: '1:28:35.200', gap: '+31.797s',  points: 8,  status: 'finished' as const },
      { position: 7,  driverId: 'GAS', time: '1:28:40.300', gap: '+36.897s',  points: 6,  status: 'finished' as const },
      { position: 8,  driverId: 'VER', time: '1:28:45.400', gap: '+41.997s',  points: 4,  status: 'finished' as const },
      { position: 9,  driverId: 'LAW', time: '1:28:50.500', gap: '+47.097s',  points: 2,  status: 'finished' as const },
      { position: 10, driverId: 'OCO', time: '1:28:55.600', gap: '+52.197s',  points: 1,  status: 'finished' as const },
      { position: 11, driverId: 'HUL', time: '1:29:00.000', gap: '+56.597s',  points: 0,  status: 'finished' as const },
      { position: 12, driverId: 'HAD', time: '1:29:05.000', gap: '+61.597s',  points: 0,  status: 'finished' as const },
      { position: 13, driverId: 'BOR', time: '1:29:10.000', gap: '+66.597s',  points: 0,  status: 'finished' as const },
      { position: 14, driverId: 'LIN', time: '1:29:15.000', gap: '+71.597s',  points: 0,  status: 'finished' as const },
      { position: 15, driverId: 'SAI', time: '1:29:20.000', gap: '+76.597s',  points: 0,  status: 'finished' as const },
      { position: 16, driverId: 'COL', time: '1:29:25.000', gap: '+81.597s',  points: 0,  status: 'finished' as const },
      { position: 17, driverId: 'PER', time: '1:29:30.000', gap: '+86.597s',  points: 0,  status: 'finished' as const },
      { position: 18, driverId: 'ALO', time: '+1 lap',       gap: '+1 lap',    points: 0,  status: 'finished' as const },
      { position: 19, driverId: 'BOT', time: '+1 lap',       gap: '+1 lap',    points: 0,  status: 'finished' as const },
      { position: 20, driverId: 'ALB', time: '+1 lap',       gap: '+1 lap',    points: 0,  status: 'finished' as const },
      { position: 21, driverId: 'STR', time: '',              gap: 'DNF',       points: 0,  status: 'dnf' as const },
      { position: 22, driverId: 'BEA', time: '',              gap: 'DNF',       points: 0,  status: 'dnf' as const },
    ],
    fastestLapDriverId: 'ANT',
    dnfDriverIds: ['STR', 'BEA'],
    dnsDriverIds: [],
  },

  // ── R04 — Miami GP — 2026-05-03 — SPRINT ────────────────────────────────
  {
    raceId: 'r04',
    classification: [
      { position: 1,  driverId: 'ANT', time: '1:33:19.273', gap: 'Leader',    points: 25, status: 'finished' as const },
      { position: 2,  driverId: 'NOR', time: '1:33:22.537', gap: '+3.264s',   points: 18, status: 'finished' as const },
      { position: 3,  driverId: 'PIA', time: '1:33:46.365', gap: '+27.092s',  points: 15, status: 'finished' as const },
      { position: 4,  driverId: 'RUS', time: '1:33:50.000', gap: '+30.727s',  points: 12, status: 'finished' as const },
      { position: 5,  driverId: 'VER', time: '1:33:55.100', gap: '+35.827s',  points: 10, status: 'finished' as const },
      { position: 6,  driverId: 'HAM', time: '1:34:00.200', gap: '+40.927s',  points: 8,  status: 'finished' as const },
      { position: 7,  driverId: 'COL', time: '1:34:10.300', gap: '+51.027s',  points: 6,  status: 'finished' as const },
      { position: 8,  driverId: 'LEC', time: '1:34:15.400', gap: '+56.127s',  points: 4,  status: 'finished' as const },
      { position: 9,  driverId: 'SAI', time: '1:34:20.500', gap: '+61.227s',  points: 2,  status: 'finished' as const },
      { position: 10, driverId: 'ALB', time: '1:34:25.600', gap: '+66.327s',  points: 1,  status: 'finished' as const },
      { position: 11, driverId: 'BEA', time: '+1 lap',       gap: '+1 lap',    points: 0,  status: 'finished' as const },
      { position: 12, driverId: 'BOR', time: '+1 lap',       gap: '+1 lap',    points: 0,  status: 'finished' as const },
      { position: 13, driverId: 'OCO', time: '+1 lap',       gap: '+1 lap',    points: 0,  status: 'finished' as const },
      { position: 14, driverId: 'LIN', time: '+1 lap',       gap: '+1 lap',    points: 0,  status: 'finished' as const },
      { position: 15, driverId: 'ALO', time: '+1 lap',       gap: '+1 lap',    points: 0,  status: 'finished' as const },
      { position: 16, driverId: 'PER', time: '+1 lap',       gap: '+1 lap',    points: 0,  status: 'finished' as const },
      { position: 17, driverId: 'STR', time: '+1 lap',       gap: '+1 lap',    points: 0,  status: 'finished' as const },
      { position: 18, driverId: 'BOT', time: '+1 lap',       gap: '+1 lap',    points: 0,  status: 'finished' as const },
      { position: 19, driverId: 'HUL', time: '',              gap: 'DNF',       points: 0,  status: 'dnf' as const },
      { position: 20, driverId: 'LAW', time: '',              gap: 'DNF',       points: 0,  status: 'dnf' as const },
      { position: 21, driverId: 'GAS', time: '',              gap: 'DNF',       points: 0,  status: 'dnf' as const },
      { position: 22, driverId: 'HAD', time: '',              gap: 'DNF',       points: 0,  status: 'dnf' as const },
    ],
    fastestLapDriverId: 'NOR',
    dnfDriverIds: ['HUL', 'LAW', 'GAS', 'HAD'],
    dnsDriverIds: [],
    sprintClassification: [
      { position: 1, driverId: 'NOR', time: '—', gap: 'Leader',  points: 8, status: 'finished' as const },
      { position: 2, driverId: 'PIA', time: '—', gap: '—',        points: 7, status: 'finished' as const },
      { position: 3, driverId: 'LEC', time: '—', gap: '—',        points: 6, status: 'finished' as const },
      { position: 4, driverId: 'RUS', time: '—', gap: '—',        points: 5, status: 'finished' as const },
      { position: 5, driverId: 'VER', time: '—', gap: '—',        points: 4, status: 'finished' as const },
      { position: 6, driverId: 'ANT', time: '—', gap: '—',        points: 3, status: 'finished' as const },
      { position: 7, driverId: 'HAM', time: '—', gap: '—',        points: 2, status: 'finished' as const },
      { position: 8, driverId: 'GAS', time: '—', gap: '—',        points: 1, status: 'finished' as const },
    ],
  },

  // ── R05 — Canadian GP — 2026-05-24 — SPRINT ─────────────────────────────
  {
    raceId: 'r05',
    classification: [
      { position: 1,  driverId: 'ANT', time: '1:28:15.758', gap: 'Leader',    points: 25, status: 'finished' as const },
      { position: 2,  driverId: 'HAM', time: '1:28:26.526', gap: '+10.768s',  points: 18, status: 'finished' as const },
      { position: 3,  driverId: 'VER', time: '1:28:28.034', gap: '+12.276s',  points: 15, status: 'finished' as const },
      { position: 4,  driverId: 'LEC', time: '1:28:35.000', gap: '+19.242s',  points: 12, status: 'finished' as const },
      { position: 5,  driverId: 'HAD', time: '+1 lap',       gap: '+1 lap',    points: 10, status: 'finished' as const },
      { position: 6,  driverId: 'COL', time: '+1 lap',       gap: '+1 lap',    points: 8,  status: 'finished' as const },
      { position: 7,  driverId: 'LAW', time: '+1 lap',       gap: '+1 lap',    points: 6,  status: 'finished' as const },
      { position: 8,  driverId: 'GAS', time: '+1 lap',       gap: '+1 lap',    points: 4,  status: 'finished' as const },
      { position: 9,  driverId: 'SAI', time: '+1 lap',       gap: '+1 lap',    points: 2,  status: 'finished' as const },
      { position: 10, driverId: 'BEA', time: '+1 lap',       gap: '+1 lap',    points: 1,  status: 'finished' as const },
      { position: 11, driverId: 'PIA', time: '+1 lap',       gap: '+1 lap',    points: 0,  status: 'finished' as const },
      { position: 12, driverId: 'HUL', time: '+1 lap',       gap: '+1 lap',    points: 0,  status: 'finished' as const },
      { position: 13, driverId: 'BOR', time: '+1 lap',       gap: '+1 lap',    points: 0,  status: 'finished' as const },
      { position: 14, driverId: 'OCO', time: '+1 lap',       gap: '+1 lap',    points: 0,  status: 'finished' as const },
      { position: 15, driverId: 'STR', time: '+1 lap',       gap: '+1 lap',    points: 0,  status: 'finished' as const },
      { position: 16, driverId: 'BOT', time: '+1 lap',       gap: '+1 lap',    points: 0,  status: 'finished' as const },
      { position: 17, driverId: 'PER', time: '',              gap: 'DNF',       points: 0,  status: 'dnf' as const },
      { position: 18, driverId: 'NOR', time: '',              gap: 'DNF',       points: 0,  status: 'dnf' as const },
      { position: 19, driverId: 'RUS', time: '',              gap: 'DNF',       points: 0,  status: 'dnf' as const },
      { position: 20, driverId: 'ALO', time: '',              gap: 'DNF',       points: 0,  status: 'dnf' as const },
      { position: 21, driverId: 'ALB', time: '',              gap: 'DNF',       points: 0,  status: 'dnf' as const },
      { position: 22, driverId: 'LIN', time: '',              gap: 'DNS',       points: 0,  status: 'dns' as const },
    ],
    fastestLapDriverId: 'ANT',
    dnfDriverIds: ['PER', 'NOR', 'RUS', 'ALO', 'ALB'],
    dnsDriverIds: ['LIN'],
    sprintClassification: [
      { position: 1, driverId: 'RUS', time: '—', gap: 'Leader',  points: 8, status: 'finished' as const },
      { position: 2, driverId: 'NOR', time: '—', gap: '—',        points: 7, status: 'finished' as const },
      { position: 3, driverId: 'ANT', time: '—', gap: '—',        points: 6, status: 'finished' as const },
      { position: 4, driverId: 'PIA', time: '—', gap: '—',        points: 5, status: 'finished' as const },
      { position: 5, driverId: 'LEC', time: '—', gap: '—',        points: 4, status: 'finished' as const },
      { position: 6, driverId: 'HAM', time: '—', gap: '—',        points: 3, status: 'finished' as const },
      { position: 7, driverId: 'VER', time: '—', gap: '—',        points: 2, status: 'finished' as const },
      { position: 8, driverId: 'LIN', time: '—', gap: '—',        points: 1, status: 'finished' as const },
    ],
  },

  // ── R06 — Monaco GP — 2026-06-07 ────────────────────────────────────────
  {
    raceId: 'r06',
    classification: [
      { position: 1,  driverId: 'ANT', time: '1:46:30.100', gap: 'Leader',   points: 25, status: 'finished' as const },
      { position: 2,  driverId: 'HAM', time: '1:46:35.200', gap: '+5.100s',   points: 18, status: 'finished' as const },
      { position: 3,  driverId: 'GAS', time: '1:46:50.300', gap: '+20.200s',  points: 15, status: 'finished' as const },
      { position: 4,  driverId: 'HAD', time: '1:46:58.400', gap: '+28.300s',  points: 12, status: 'finished' as const },
      { position: 5,  driverId: 'PIA', time: '1:47:05.500', gap: '+35.400s',  points: 10, status: 'finished' as const },
      { position: 6,  driverId: 'LAW', time: '1:47:12.600', gap: '+42.500s',  points: 8,  status: 'finished' as const },
      { position: 7,  driverId: 'LIN', time: '1:47:20.700', gap: '+50.600s',  points: 6,  status: 'finished' as const },
      { position: 8,  driverId: 'ALB', time: '1:47:28.800', gap: '+58.700s',  points: 4,  status: 'finished' as const },
      { position: 9,  driverId: 'OCO', time: '1:47:36.900', gap: '+66.800s',  points: 2,  status: 'finished' as const },
      { position: 10, driverId: 'ALO', time: '1:47:45.000', gap: '+74.900s',  points: 1,  status: 'finished' as const },
      { position: 11, driverId: 'BOR', time: '1:47:53.000', gap: '+82.900s',  points: 0,  status: 'finished' as const },
      { position: 12, driverId: 'RUS', time: '1:48:01.000', gap: '+90.900s',  points: 0,  status: 'finished' as const },
      { position: 13, driverId: 'HUL', time: '1:48:09.000', gap: '+98.900s',  points: 0,  status: 'finished' as const },
      { position: 14, driverId: 'COL', time: '1:48:17.000', gap: '+106.900s', points: 0,  status: 'finished' as const },
      { position: 15, driverId: 'PER', time: '1:48:25.000', gap: '+114.900s', points: 0,  status: 'finished' as const },
      { position: 16, driverId: 'SAI', time: '',              gap: 'DNF',       points: 0,  status: 'dnf' as const },
      { position: 17, driverId: 'LEC', time: '',              gap: 'DNF',       points: 0,  status: 'dnf' as const },
      { position: 18, driverId: 'STR', time: '',              gap: 'DNF',       points: 0,  status: 'dnf' as const },
      { position: 19, driverId: 'NOR', time: '',              gap: 'DNF',       points: 0,  status: 'dnf' as const },
      { position: 20, driverId: 'BEA', time: '',              gap: 'DNF',       points: 0,  status: 'dnf' as const },
      { position: 21, driverId: 'BOT', time: '',              gap: 'DNF',       points: 0,  status: 'dnf' as const },
      { position: 22, driverId: 'VER', time: '',              gap: 'DNF',       points: 0,  status: 'dnf' as const },
    ],
    fastestLapDriverId: 'ANT',
    dnfDriverIds: ['SAI', 'LEC', 'STR', 'NOR', 'BEA', 'BOT', 'VER'],
    dnsDriverIds: [],
  },

  // ── R07 — Barcelona GP — 2026-06-14 ─────────────────────────────────────
  {
    raceId: 'r07',
    classification: [
      { position: 1,  driverId: 'HAM', time: '1:29:55.100', gap: 'Leader',   points: 25, status: 'finished' as const },
      { position: 2,  driverId: 'RUS', time: '1:30:02.200', gap: '+7.100s',   points: 18, status: 'finished' as const },
      { position: 3,  driverId: 'NOR', time: '1:30:12.300', gap: '+17.200s',  points: 15, status: 'finished' as const },
      { position: 4,  driverId: 'VER', time: '1:30:25.400', gap: '+30.300s',  points: 12, status: 'finished' as const },
      { position: 5,  driverId: 'PIA', time: '1:30:38.500', gap: '+43.400s',  points: 10, status: 'finished' as const },
      { position: 6,  driverId: 'HAD', time: '+1 lap',       gap: '+1 lap',    points: 8,  status: 'finished' as const },
      { position: 7,  driverId: 'GAS', time: '+1 lap',       gap: '+1 lap',    points: 6,  status: 'finished' as const },
      { position: 8,  driverId: 'LAW', time: '+1 lap',       gap: '+1 lap',    points: 4,  status: 'finished' as const },
      { position: 9,  driverId: 'LIN', time: '+1 lap',       gap: '+1 lap',    points: 2,  status: 'finished' as const },
      { position: 10, driverId: 'COL', time: '+1 lap',       gap: '+1 lap',    points: 1,  status: 'finished' as const },
      { position: 11, driverId: 'BOR', time: '+1 lap',       gap: '+1 lap',    points: 0,  status: 'finished' as const },
      { position: 12, driverId: 'SAI', time: '+1 lap',       gap: '+1 lap',    points: 0,  status: 'finished' as const },
      { position: 13, driverId: 'OCO', time: '+1 lap',       gap: '+1 lap',    points: 0,  status: 'finished' as const },
      { position: 14, driverId: 'PER', time: '+1 lap',       gap: '+1 lap',    points: 0,  status: 'finished' as const },
      { position: 15, driverId: 'LEC', time: '',              gap: 'DNF',       points: 0,  status: 'dnf' as const },
      { position: 16, driverId: 'ANT', time: '',              gap: 'DNF',       points: 0,  status: 'dnf' as const },
      { position: 17, driverId: 'BEA', time: '',              gap: 'DNF',       points: 0,  status: 'dnf' as const },
      { position: 18, driverId: 'ALB', time: '+1 lap',       gap: '+1 lap',    points: 0,  status: 'finished' as const },
      { position: 19, driverId: 'ALO', time: '',              gap: 'DNF',       points: 0,  status: 'dnf' as const },
      { position: 20, driverId: 'HUL', time: '',              gap: 'DNF',       points: 0,  status: 'dnf' as const },
      { position: 21, driverId: 'BOT', time: '',              gap: 'DNF',       points: 0,  status: 'dnf' as const },
      { position: 22, driverId: 'STR', time: '',              gap: 'DNF',       points: 0,  status: 'dnf' as const },
    ],
    fastestLapDriverId: 'HAM',
    dnfDriverIds: ['LEC', 'ANT', 'BEA', 'ALO', 'HUL', 'BOT', 'STR'],
    dnsDriverIds: [],
  },
];
